// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProtoFiles/CameraInfo/AUDIO_CAPABILITY_DATA_VGPB.proto

package com.aolais.electroraven.is2viewerbeta.protos;

public final class AudioCapabilityDataVGPB {
  private AudioCapabilityDataVGPB() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface AUDIO_CAPABILITY_DATA_VGPBOrBuilder extends
      // @@protoc_insertion_point(interface_extends:AUDIO_CAPABILITY_DATA_VGPB)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 maxInCameraAudioDurationSecs = 1;</code>
     */
    boolean hasMaxInCameraAudioDurationSecs();
    /**
     * <code>required int32 maxInCameraAudioDurationSecs = 1;</code>
     */
    int getMaxInCameraAudioDurationSecs();

    /**
     * <code>required int32 audioDataFormat = 2;</code>
     */
    boolean hasAudioDataFormat();
    /**
     * <code>required int32 audioDataFormat = 2;</code>
     */
    int getAudioDataFormat();
  }
  /**
   * Protobuf type {@code AUDIO_CAPABILITY_DATA_VGPB}
   */
  public static final class AUDIO_CAPABILITY_DATA_VGPB extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:AUDIO_CAPABILITY_DATA_VGPB)
      AUDIO_CAPABILITY_DATA_VGPBOrBuilder {
    // Use AUDIO_CAPABILITY_DATA_VGPB.newBuilder() to construct.
    private AUDIO_CAPABILITY_DATA_VGPB(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private AUDIO_CAPABILITY_DATA_VGPB(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final AUDIO_CAPABILITY_DATA_VGPB defaultInstance;
    public static AUDIO_CAPABILITY_DATA_VGPB getDefaultInstance() {
      return defaultInstance;
    }

    public AUDIO_CAPABILITY_DATA_VGPB getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private AUDIO_CAPABILITY_DATA_VGPB(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              maxInCameraAudioDurationSecs_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              audioDataFormat_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.aolais.electroraven.is2viewerbeta.protos.AudioCapabilityDataVGPB.internal_static_AUDIO_CAPABILITY_DATA_VGPB_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.aolais.electroraven.is2viewerbeta.protos.AudioCapabilityDataVGPB.internal_static_AUDIO_CAPABILITY_DATA_VGPB_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.aolais.electroraven.is2viewerbeta.protos.AudioCapabilityDataVGPB.AUDIO_CAPABILITY_DATA_VGPB.class, com.aolais.electroraven.is2viewerbeta.protos.AudioCapabilityDataVGPB.AUDIO_CAPABILITY_DATA_VGPB.Builder.class);
    }

    public static com.google.protobuf.Parser<AUDIO_CAPABILITY_DATA_VGPB> PARSER =
        new com.google.protobuf.AbstractParser<AUDIO_CAPABILITY_DATA_VGPB>() {
      public AUDIO_CAPABILITY_DATA_VGPB parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new AUDIO_CAPABILITY_DATA_VGPB(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<AUDIO_CAPABILITY_DATA_VGPB> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int MAXINCAMERAAUDIODURATIONSECS_FIELD_NUMBER = 1;
    private int maxInCameraAudioDurationSecs_;
    /**
     * <code>required int32 maxInCameraAudioDurationSecs = 1;</code>
     */
    public boolean hasMaxInCameraAudioDurationSecs() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 maxInCameraAudioDurationSecs = 1;</code>
     */
    public int getMaxInCameraAudioDurationSecs() {
      return maxInCameraAudioDurationSecs_;
    }

    public static final int AUDIODATAFORMAT_FIELD_NUMBER = 2;
    private int audioDataFormat_;
    /**
     * <code>required int32 audioDataFormat = 2;</code>
     */
    public boolean hasAudioDataFormat() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 audioDataFormat = 2;</code>
     */
    public int getAudioDataFormat() {
      return audioDataFormat_;
    }

    private void initFields() {
      maxInCameraAudioDurationSecs_ = 0;
      audioDataFormat_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasMaxInCameraAudioDurationSecs()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasAudioDataFormat()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, maxInCameraAudioDurationSecs_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, audioDataFormat_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, maxInCameraAudioDurationSecs_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, audioDataFormat_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.aolais.electroraven.is2viewerbeta.protos.AudioCapabilityDataVGPB.AUDIO_CAPABILITY_DATA_VGPB parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.aolais.electroraven.is2viewerbeta.protos.AudioCapabilityDataVGPB.AUDIO_CAPABILITY_DATA_VGPB parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.aolais.electroraven.is2viewerbeta.protos.AudioCapabilityDataVGPB.AUDIO_CAPABILITY_DATA_VGPB parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.aolais.electroraven.is2viewerbeta.protos.AudioCapabilityDataVGPB.AUDIO_CAPABILITY_DATA_VGPB parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.aolais.electroraven.is2viewerbeta.protos.AudioCapabilityDataVGPB.AUDIO_CAPABILITY_DATA_VGPB parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.aolais.electroraven.is2viewerbeta.protos.AudioCapabilityDataVGPB.AUDIO_CAPABILITY_DATA_VGPB parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.aolais.electroraven.is2viewerbeta.protos.AudioCapabilityDataVGPB.AUDIO_CAPABILITY_DATA_VGPB parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.aolais.electroraven.is2viewerbeta.protos.AudioCapabilityDataVGPB.AUDIO_CAPABILITY_DATA_VGPB parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.aolais.electroraven.is2viewerbeta.protos.AudioCapabilityDataVGPB.AUDIO_CAPABILITY_DATA_VGPB parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.aolais.electroraven.is2viewerbeta.protos.AudioCapabilityDataVGPB.AUDIO_CAPABILITY_DATA_VGPB parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.aolais.electroraven.is2viewerbeta.protos.AudioCapabilityDataVGPB.AUDIO_CAPABILITY_DATA_VGPB prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code AUDIO_CAPABILITY_DATA_VGPB}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:AUDIO_CAPABILITY_DATA_VGPB)
        com.aolais.electroraven.is2viewerbeta.protos.AudioCapabilityDataVGPB.AUDIO_CAPABILITY_DATA_VGPBOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.aolais.electroraven.is2viewerbeta.protos.AudioCapabilityDataVGPB.internal_static_AUDIO_CAPABILITY_DATA_VGPB_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.aolais.electroraven.is2viewerbeta.protos.AudioCapabilityDataVGPB.internal_static_AUDIO_CAPABILITY_DATA_VGPB_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.aolais.electroraven.is2viewerbeta.protos.AudioCapabilityDataVGPB.AUDIO_CAPABILITY_DATA_VGPB.class, com.aolais.electroraven.is2viewerbeta.protos.AudioCapabilityDataVGPB.AUDIO_CAPABILITY_DATA_VGPB.Builder.class);
      }

      // Construct using com.aolais.electroraven.is2viewerbeta.protos.AudioCapabilityDataVGPB.AUDIO_CAPABILITY_DATA_VGPB.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        maxInCameraAudioDurationSecs_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        audioDataFormat_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.aolais.electroraven.is2viewerbeta.protos.AudioCapabilityDataVGPB.internal_static_AUDIO_CAPABILITY_DATA_VGPB_descriptor;
      }

      public com.aolais.electroraven.is2viewerbeta.protos.AudioCapabilityDataVGPB.AUDIO_CAPABILITY_DATA_VGPB getDefaultInstanceForType() {
        return com.aolais.electroraven.is2viewerbeta.protos.AudioCapabilityDataVGPB.AUDIO_CAPABILITY_DATA_VGPB.getDefaultInstance();
      }

      public com.aolais.electroraven.is2viewerbeta.protos.AudioCapabilityDataVGPB.AUDIO_CAPABILITY_DATA_VGPB build() {
        com.aolais.electroraven.is2viewerbeta.protos.AudioCapabilityDataVGPB.AUDIO_CAPABILITY_DATA_VGPB result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.aolais.electroraven.is2viewerbeta.protos.AudioCapabilityDataVGPB.AUDIO_CAPABILITY_DATA_VGPB buildPartial() {
        com.aolais.electroraven.is2viewerbeta.protos.AudioCapabilityDataVGPB.AUDIO_CAPABILITY_DATA_VGPB result = new com.aolais.electroraven.is2viewerbeta.protos.AudioCapabilityDataVGPB.AUDIO_CAPABILITY_DATA_VGPB(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.maxInCameraAudioDurationSecs_ = maxInCameraAudioDurationSecs_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.audioDataFormat_ = audioDataFormat_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.aolais.electroraven.is2viewerbeta.protos.AudioCapabilityDataVGPB.AUDIO_CAPABILITY_DATA_VGPB) {
          return mergeFrom((com.aolais.electroraven.is2viewerbeta.protos.AudioCapabilityDataVGPB.AUDIO_CAPABILITY_DATA_VGPB)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.aolais.electroraven.is2viewerbeta.protos.AudioCapabilityDataVGPB.AUDIO_CAPABILITY_DATA_VGPB other) {
        if (other == com.aolais.electroraven.is2viewerbeta.protos.AudioCapabilityDataVGPB.AUDIO_CAPABILITY_DATA_VGPB.getDefaultInstance()) return this;
        if (other.hasMaxInCameraAudioDurationSecs()) {
          setMaxInCameraAudioDurationSecs(other.getMaxInCameraAudioDurationSecs());
        }
        if (other.hasAudioDataFormat()) {
          setAudioDataFormat(other.getAudioDataFormat());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasMaxInCameraAudioDurationSecs()) {
          
          return false;
        }
        if (!hasAudioDataFormat()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.aolais.electroraven.is2viewerbeta.protos.AudioCapabilityDataVGPB.AUDIO_CAPABILITY_DATA_VGPB parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.aolais.electroraven.is2viewerbeta.protos.AudioCapabilityDataVGPB.AUDIO_CAPABILITY_DATA_VGPB) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int maxInCameraAudioDurationSecs_ ;
      /**
       * <code>required int32 maxInCameraAudioDurationSecs = 1;</code>
       */
      public boolean hasMaxInCameraAudioDurationSecs() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 maxInCameraAudioDurationSecs = 1;</code>
       */
      public int getMaxInCameraAudioDurationSecs() {
        return maxInCameraAudioDurationSecs_;
      }
      /**
       * <code>required int32 maxInCameraAudioDurationSecs = 1;</code>
       */
      public Builder setMaxInCameraAudioDurationSecs(int value) {
        bitField0_ |= 0x00000001;
        maxInCameraAudioDurationSecs_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 maxInCameraAudioDurationSecs = 1;</code>
       */
      public Builder clearMaxInCameraAudioDurationSecs() {
        bitField0_ = (bitField0_ & ~0x00000001);
        maxInCameraAudioDurationSecs_ = 0;
        onChanged();
        return this;
      }

      private int audioDataFormat_ ;
      /**
       * <code>required int32 audioDataFormat = 2;</code>
       */
      public boolean hasAudioDataFormat() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 audioDataFormat = 2;</code>
       */
      public int getAudioDataFormat() {
        return audioDataFormat_;
      }
      /**
       * <code>required int32 audioDataFormat = 2;</code>
       */
      public Builder setAudioDataFormat(int value) {
        bitField0_ |= 0x00000002;
        audioDataFormat_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 audioDataFormat = 2;</code>
       */
      public Builder clearAudioDataFormat() {
        bitField0_ = (bitField0_ & ~0x00000002);
        audioDataFormat_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:AUDIO_CAPABILITY_DATA_VGPB)
    }

    static {
      defaultInstance = new AUDIO_CAPABILITY_DATA_VGPB(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:AUDIO_CAPABILITY_DATA_VGPB)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AUDIO_CAPABILITY_DATA_VGPB_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_AUDIO_CAPABILITY_DATA_VGPB_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n6ProtoFiles/CameraInfo/AUDIO_CAPABILITY" +
      "_DATA_VGPB.proto\"[\n\032AUDIO_CAPABILITY_DAT" +
      "A_VGPB\022$\n\034maxInCameraAudioDurationSecs\030\001" +
      " \002(\005\022\027\n\017audioDataFormat\030\002 \002(\005BG\n,com.aol" +
      "ais.electroraven.is2viewerbeta.protosB\027A" +
      "udioCapabilityDataVGPB"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_AUDIO_CAPABILITY_DATA_VGPB_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_AUDIO_CAPABILITY_DATA_VGPB_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_AUDIO_CAPABILITY_DATA_VGPB_descriptor,
        new java.lang.String[] { "MaxInCameraAudioDurationSecs", "AudioDataFormat", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
