// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProtoFiles/CameraInfo/CALIBRATION_DATE.proto

package com.aolais.electroraven.is2viewerbeta.protos;

public final class CalibrationDate {
  private CalibrationDate() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface CALIBRATION_DATEOrBuilder extends
      // @@protoc_insertion_point(interface_extends:CALIBRATION_DATE)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 calibrationYear4Digits = 1;</code>
     */
    boolean hasCalibrationYear4Digits();
    /**
     * <code>required int32 calibrationYear4Digits = 1;</code>
     */
    int getCalibrationYear4Digits();

    /**
     * <code>required int32 calibrationMonth = 2;</code>
     */
    boolean hasCalibrationMonth();
    /**
     * <code>required int32 calibrationMonth = 2;</code>
     */
    int getCalibrationMonth();

    /**
     * <code>required int32 calibrationDay = 3;</code>
     */
    boolean hasCalibrationDay();
    /**
     * <code>required int32 calibrationDay = 3;</code>
     */
    int getCalibrationDay();

    /**
     * <code>required int32 ccalibrationRun = 4;</code>
     */
    boolean hasCcalibrationRun();
    /**
     * <code>required int32 ccalibrationRun = 4;</code>
     */
    int getCcalibrationRun();
  }
  /**
   * Protobuf type {@code CALIBRATION_DATE}
   */
  public static final class CALIBRATION_DATE extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:CALIBRATION_DATE)
      CALIBRATION_DATEOrBuilder {
    // Use CALIBRATION_DATE.newBuilder() to construct.
    private CALIBRATION_DATE(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private CALIBRATION_DATE(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final CALIBRATION_DATE defaultInstance;
    public static CALIBRATION_DATE getDefaultInstance() {
      return defaultInstance;
    }

    public CALIBRATION_DATE getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private CALIBRATION_DATE(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              calibrationYear4Digits_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              calibrationMonth_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              calibrationDay_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              ccalibrationRun_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.aolais.electroraven.is2viewerbeta.protos.CalibrationDate.internal_static_CALIBRATION_DATE_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.aolais.electroraven.is2viewerbeta.protos.CalibrationDate.internal_static_CALIBRATION_DATE_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.aolais.electroraven.is2viewerbeta.protos.CalibrationDate.CALIBRATION_DATE.class, com.aolais.electroraven.is2viewerbeta.protos.CalibrationDate.CALIBRATION_DATE.Builder.class);
    }

    public static com.google.protobuf.Parser<CALIBRATION_DATE> PARSER =
        new com.google.protobuf.AbstractParser<CALIBRATION_DATE>() {
      public CALIBRATION_DATE parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CALIBRATION_DATE(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<CALIBRATION_DATE> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int CALIBRATIONYEAR4DIGITS_FIELD_NUMBER = 1;
    private int calibrationYear4Digits_;
    /**
     * <code>required int32 calibrationYear4Digits = 1;</code>
     */
    public boolean hasCalibrationYear4Digits() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 calibrationYear4Digits = 1;</code>
     */
    public int getCalibrationYear4Digits() {
      return calibrationYear4Digits_;
    }

    public static final int CALIBRATIONMONTH_FIELD_NUMBER = 2;
    private int calibrationMonth_;
    /**
     * <code>required int32 calibrationMonth = 2;</code>
     */
    public boolean hasCalibrationMonth() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 calibrationMonth = 2;</code>
     */
    public int getCalibrationMonth() {
      return calibrationMonth_;
    }

    public static final int CALIBRATIONDAY_FIELD_NUMBER = 3;
    private int calibrationDay_;
    /**
     * <code>required int32 calibrationDay = 3;</code>
     */
    public boolean hasCalibrationDay() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int32 calibrationDay = 3;</code>
     */
    public int getCalibrationDay() {
      return calibrationDay_;
    }

    public static final int CCALIBRATIONRUN_FIELD_NUMBER = 4;
    private int ccalibrationRun_;
    /**
     * <code>required int32 ccalibrationRun = 4;</code>
     */
    public boolean hasCcalibrationRun() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required int32 ccalibrationRun = 4;</code>
     */
    public int getCcalibrationRun() {
      return ccalibrationRun_;
    }

    private void initFields() {
      calibrationYear4Digits_ = 0;
      calibrationMonth_ = 0;
      calibrationDay_ = 0;
      ccalibrationRun_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasCalibrationYear4Digits()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCalibrationMonth()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCalibrationDay()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCcalibrationRun()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, calibrationYear4Digits_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, calibrationMonth_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, calibrationDay_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, ccalibrationRun_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, calibrationYear4Digits_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, calibrationMonth_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, calibrationDay_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, ccalibrationRun_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.aolais.electroraven.is2viewerbeta.protos.CalibrationDate.CALIBRATION_DATE parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.aolais.electroraven.is2viewerbeta.protos.CalibrationDate.CALIBRATION_DATE parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.aolais.electroraven.is2viewerbeta.protos.CalibrationDate.CALIBRATION_DATE parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.aolais.electroraven.is2viewerbeta.protos.CalibrationDate.CALIBRATION_DATE parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.aolais.electroraven.is2viewerbeta.protos.CalibrationDate.CALIBRATION_DATE parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.aolais.electroraven.is2viewerbeta.protos.CalibrationDate.CALIBRATION_DATE parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.aolais.electroraven.is2viewerbeta.protos.CalibrationDate.CALIBRATION_DATE parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.aolais.electroraven.is2viewerbeta.protos.CalibrationDate.CALIBRATION_DATE parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.aolais.electroraven.is2viewerbeta.protos.CalibrationDate.CALIBRATION_DATE parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.aolais.electroraven.is2viewerbeta.protos.CalibrationDate.CALIBRATION_DATE parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.aolais.electroraven.is2viewerbeta.protos.CalibrationDate.CALIBRATION_DATE prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code CALIBRATION_DATE}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:CALIBRATION_DATE)
        com.aolais.electroraven.is2viewerbeta.protos.CalibrationDate.CALIBRATION_DATEOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.aolais.electroraven.is2viewerbeta.protos.CalibrationDate.internal_static_CALIBRATION_DATE_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.aolais.electroraven.is2viewerbeta.protos.CalibrationDate.internal_static_CALIBRATION_DATE_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.aolais.electroraven.is2viewerbeta.protos.CalibrationDate.CALIBRATION_DATE.class, com.aolais.electroraven.is2viewerbeta.protos.CalibrationDate.CALIBRATION_DATE.Builder.class);
      }

      // Construct using com.aolais.electroraven.is2viewerbeta.protos.CalibrationDate.CALIBRATION_DATE.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        calibrationYear4Digits_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        calibrationMonth_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        calibrationDay_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        ccalibrationRun_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.aolais.electroraven.is2viewerbeta.protos.CalibrationDate.internal_static_CALIBRATION_DATE_descriptor;
      }

      public com.aolais.electroraven.is2viewerbeta.protos.CalibrationDate.CALIBRATION_DATE getDefaultInstanceForType() {
        return com.aolais.electroraven.is2viewerbeta.protos.CalibrationDate.CALIBRATION_DATE.getDefaultInstance();
      }

      public com.aolais.electroraven.is2viewerbeta.protos.CalibrationDate.CALIBRATION_DATE build() {
        com.aolais.electroraven.is2viewerbeta.protos.CalibrationDate.CALIBRATION_DATE result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.aolais.electroraven.is2viewerbeta.protos.CalibrationDate.CALIBRATION_DATE buildPartial() {
        com.aolais.electroraven.is2viewerbeta.protos.CalibrationDate.CALIBRATION_DATE result = new com.aolais.electroraven.is2viewerbeta.protos.CalibrationDate.CALIBRATION_DATE(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.calibrationYear4Digits_ = calibrationYear4Digits_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.calibrationMonth_ = calibrationMonth_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.calibrationDay_ = calibrationDay_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.ccalibrationRun_ = ccalibrationRun_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.aolais.electroraven.is2viewerbeta.protos.CalibrationDate.CALIBRATION_DATE) {
          return mergeFrom((com.aolais.electroraven.is2viewerbeta.protos.CalibrationDate.CALIBRATION_DATE)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.aolais.electroraven.is2viewerbeta.protos.CalibrationDate.CALIBRATION_DATE other) {
        if (other == com.aolais.electroraven.is2viewerbeta.protos.CalibrationDate.CALIBRATION_DATE.getDefaultInstance()) return this;
        if (other.hasCalibrationYear4Digits()) {
          setCalibrationYear4Digits(other.getCalibrationYear4Digits());
        }
        if (other.hasCalibrationMonth()) {
          setCalibrationMonth(other.getCalibrationMonth());
        }
        if (other.hasCalibrationDay()) {
          setCalibrationDay(other.getCalibrationDay());
        }
        if (other.hasCcalibrationRun()) {
          setCcalibrationRun(other.getCcalibrationRun());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasCalibrationYear4Digits()) {
          
          return false;
        }
        if (!hasCalibrationMonth()) {
          
          return false;
        }
        if (!hasCalibrationDay()) {
          
          return false;
        }
        if (!hasCcalibrationRun()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.aolais.electroraven.is2viewerbeta.protos.CalibrationDate.CALIBRATION_DATE parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.aolais.electroraven.is2viewerbeta.protos.CalibrationDate.CALIBRATION_DATE) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int calibrationYear4Digits_ ;
      /**
       * <code>required int32 calibrationYear4Digits = 1;</code>
       */
      public boolean hasCalibrationYear4Digits() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 calibrationYear4Digits = 1;</code>
       */
      public int getCalibrationYear4Digits() {
        return calibrationYear4Digits_;
      }
      /**
       * <code>required int32 calibrationYear4Digits = 1;</code>
       */
      public Builder setCalibrationYear4Digits(int value) {
        bitField0_ |= 0x00000001;
        calibrationYear4Digits_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 calibrationYear4Digits = 1;</code>
       */
      public Builder clearCalibrationYear4Digits() {
        bitField0_ = (bitField0_ & ~0x00000001);
        calibrationYear4Digits_ = 0;
        onChanged();
        return this;
      }

      private int calibrationMonth_ ;
      /**
       * <code>required int32 calibrationMonth = 2;</code>
       */
      public boolean hasCalibrationMonth() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 calibrationMonth = 2;</code>
       */
      public int getCalibrationMonth() {
        return calibrationMonth_;
      }
      /**
       * <code>required int32 calibrationMonth = 2;</code>
       */
      public Builder setCalibrationMonth(int value) {
        bitField0_ |= 0x00000002;
        calibrationMonth_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 calibrationMonth = 2;</code>
       */
      public Builder clearCalibrationMonth() {
        bitField0_ = (bitField0_ & ~0x00000002);
        calibrationMonth_ = 0;
        onChanged();
        return this;
      }

      private int calibrationDay_ ;
      /**
       * <code>required int32 calibrationDay = 3;</code>
       */
      public boolean hasCalibrationDay() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int32 calibrationDay = 3;</code>
       */
      public int getCalibrationDay() {
        return calibrationDay_;
      }
      /**
       * <code>required int32 calibrationDay = 3;</code>
       */
      public Builder setCalibrationDay(int value) {
        bitField0_ |= 0x00000004;
        calibrationDay_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 calibrationDay = 3;</code>
       */
      public Builder clearCalibrationDay() {
        bitField0_ = (bitField0_ & ~0x00000004);
        calibrationDay_ = 0;
        onChanged();
        return this;
      }

      private int ccalibrationRun_ ;
      /**
       * <code>required int32 ccalibrationRun = 4;</code>
       */
      public boolean hasCcalibrationRun() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required int32 ccalibrationRun = 4;</code>
       */
      public int getCcalibrationRun() {
        return ccalibrationRun_;
      }
      /**
       * <code>required int32 ccalibrationRun = 4;</code>
       */
      public Builder setCcalibrationRun(int value) {
        bitField0_ |= 0x00000008;
        ccalibrationRun_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 ccalibrationRun = 4;</code>
       */
      public Builder clearCcalibrationRun() {
        bitField0_ = (bitField0_ & ~0x00000008);
        ccalibrationRun_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:CALIBRATION_DATE)
    }

    static {
      defaultInstance = new CALIBRATION_DATE(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:CALIBRATION_DATE)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CALIBRATION_DATE_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_CALIBRATION_DATE_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n,ProtoFiles/CameraInfo/CALIBRATION_DATE" +
      ".proto\"}\n\020CALIBRATION_DATE\022\036\n\026calibratio" +
      "nYear4Digits\030\001 \002(\005\022\030\n\020calibrationMonth\030\002" +
      " \002(\005\022\026\n\016calibrationDay\030\003 \002(\005\022\027\n\017ccalibra" +
      "tionRun\030\004 \002(\005B?\n,com.aolais.electroraven" +
      ".is2viewerbeta.protosB\017CalibrationDate"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_CALIBRATION_DATE_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_CALIBRATION_DATE_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_CALIBRATION_DATE_descriptor,
        new java.lang.String[] { "CalibrationYear4Digits", "CalibrationMonth", "CalibrationDay", "CcalibrationRun", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
