// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GEMINI_UINVERSE_CURVE_DESCRIPTOR_VGPB.proto

package com.aolais.electroraven.is2viewerbeta.protos;

public final class GeminiUniverseCurveDescriptorVGPB {
  private GeminiUniverseCurveDescriptorVGPB() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface GEMINI_UINVERSE_CURVE_DESCRIPTOR_VGPBOrBuilder extends
      // @@protoc_insertion_point(interface_extends:GEMINI_UINVERSE_CURVE_DESCRIPTOR_VGPB)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required float startTempC = 1;</code>
     */
    boolean hasStartTempC();
    /**
     * <code>required float startTempC = 1;</code>
     */
    float getStartTempC();

    /**
     * <code>required float endTempC = 2;</code>
     */
    boolean hasEndTempC();
    /**
     * <code>required float endTempC = 2;</code>
     */
    float getEndTempC();

    /**
     * <code>required float U0 = 3;</code>
     */
    boolean hasU0();
    /**
     * <code>required float U0 = 3;</code>
     */
    float getU0();

    /**
     * <code>required float U1 = 4;</code>
     */
    boolean hasU1();
    /**
     * <code>required float U1 = 4;</code>
     */
    float getU1();

    /**
     * <code>required float U2 = 5;</code>
     */
    boolean hasU2();
    /**
     * <code>required float U2 = 5;</code>
     */
    float getU2();
  }
  /**
   * Protobuf type {@code GEMINI_UINVERSE_CURVE_DESCRIPTOR_VGPB}
   */
  public static final class GEMINI_UINVERSE_CURVE_DESCRIPTOR_VGPB extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:GEMINI_UINVERSE_CURVE_DESCRIPTOR_VGPB)
      GEMINI_UINVERSE_CURVE_DESCRIPTOR_VGPBOrBuilder {
    // Use GEMINI_UINVERSE_CURVE_DESCRIPTOR_VGPB.newBuilder() to construct.
    private GEMINI_UINVERSE_CURVE_DESCRIPTOR_VGPB(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private GEMINI_UINVERSE_CURVE_DESCRIPTOR_VGPB(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final GEMINI_UINVERSE_CURVE_DESCRIPTOR_VGPB defaultInstance;
    public static GEMINI_UINVERSE_CURVE_DESCRIPTOR_VGPB getDefaultInstance() {
      return defaultInstance;
    }

    public GEMINI_UINVERSE_CURVE_DESCRIPTOR_VGPB getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private GEMINI_UINVERSE_CURVE_DESCRIPTOR_VGPB(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 13: {
              bitField0_ |= 0x00000001;
              startTempC_ = input.readFloat();
              break;
            }
            case 21: {
              bitField0_ |= 0x00000002;
              endTempC_ = input.readFloat();
              break;
            }
            case 29: {
              bitField0_ |= 0x00000004;
              u0_ = input.readFloat();
              break;
            }
            case 37: {
              bitField0_ |= 0x00000008;
              u1_ = input.readFloat();
              break;
            }
            case 45: {
              bitField0_ |= 0x00000010;
              u2_ = input.readFloat();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.aolais.electroraven.is2viewerbeta.protos.GeminiUniverseCurveDescriptorVGPB.internal_static_GEMINI_UINVERSE_CURVE_DESCRIPTOR_VGPB_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.aolais.electroraven.is2viewerbeta.protos.GeminiUniverseCurveDescriptorVGPB.internal_static_GEMINI_UINVERSE_CURVE_DESCRIPTOR_VGPB_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.aolais.electroraven.is2viewerbeta.protos.GeminiUniverseCurveDescriptorVGPB.GEMINI_UINVERSE_CURVE_DESCRIPTOR_VGPB.class, com.aolais.electroraven.is2viewerbeta.protos.GeminiUniverseCurveDescriptorVGPB.GEMINI_UINVERSE_CURVE_DESCRIPTOR_VGPB.Builder.class);
    }

    public static com.google.protobuf.Parser<GEMINI_UINVERSE_CURVE_DESCRIPTOR_VGPB> PARSER =
        new com.google.protobuf.AbstractParser<GEMINI_UINVERSE_CURVE_DESCRIPTOR_VGPB>() {
      public GEMINI_UINVERSE_CURVE_DESCRIPTOR_VGPB parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GEMINI_UINVERSE_CURVE_DESCRIPTOR_VGPB(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<GEMINI_UINVERSE_CURVE_DESCRIPTOR_VGPB> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int STARTTEMPC_FIELD_NUMBER = 1;
    private float startTempC_;
    /**
     * <code>required float startTempC = 1;</code>
     */
    public boolean hasStartTempC() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required float startTempC = 1;</code>
     */
    public float getStartTempC() {
      return startTempC_;
    }

    public static final int ENDTEMPC_FIELD_NUMBER = 2;
    private float endTempC_;
    /**
     * <code>required float endTempC = 2;</code>
     */
    public boolean hasEndTempC() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required float endTempC = 2;</code>
     */
    public float getEndTempC() {
      return endTempC_;
    }

    public static final int U0_FIELD_NUMBER = 3;
    private float u0_;
    /**
     * <code>required float U0 = 3;</code>
     */
    public boolean hasU0() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required float U0 = 3;</code>
     */
    public float getU0() {
      return u0_;
    }

    public static final int U1_FIELD_NUMBER = 4;
    private float u1_;
    /**
     * <code>required float U1 = 4;</code>
     */
    public boolean hasU1() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required float U1 = 4;</code>
     */
    public float getU1() {
      return u1_;
    }

    public static final int U2_FIELD_NUMBER = 5;
    private float u2_;
    /**
     * <code>required float U2 = 5;</code>
     */
    public boolean hasU2() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required float U2 = 5;</code>
     */
    public float getU2() {
      return u2_;
    }

    private void initFields() {
      startTempC_ = 0F;
      endTempC_ = 0F;
      u0_ = 0F;
      u1_ = 0F;
      u2_ = 0F;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasStartTempC()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasEndTempC()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasU0()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasU1()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasU2()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeFloat(1, startTempC_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeFloat(2, endTempC_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeFloat(3, u0_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeFloat(4, u1_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeFloat(5, u2_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(1, startTempC_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(2, endTempC_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(3, u0_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(4, u1_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(5, u2_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.aolais.electroraven.is2viewerbeta.protos.GeminiUniverseCurveDescriptorVGPB.GEMINI_UINVERSE_CURVE_DESCRIPTOR_VGPB parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.aolais.electroraven.is2viewerbeta.protos.GeminiUniverseCurveDescriptorVGPB.GEMINI_UINVERSE_CURVE_DESCRIPTOR_VGPB parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.aolais.electroraven.is2viewerbeta.protos.GeminiUniverseCurveDescriptorVGPB.GEMINI_UINVERSE_CURVE_DESCRIPTOR_VGPB parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.aolais.electroraven.is2viewerbeta.protos.GeminiUniverseCurveDescriptorVGPB.GEMINI_UINVERSE_CURVE_DESCRIPTOR_VGPB parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.aolais.electroraven.is2viewerbeta.protos.GeminiUniverseCurveDescriptorVGPB.GEMINI_UINVERSE_CURVE_DESCRIPTOR_VGPB parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.aolais.electroraven.is2viewerbeta.protos.GeminiUniverseCurveDescriptorVGPB.GEMINI_UINVERSE_CURVE_DESCRIPTOR_VGPB parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.aolais.electroraven.is2viewerbeta.protos.GeminiUniverseCurveDescriptorVGPB.GEMINI_UINVERSE_CURVE_DESCRIPTOR_VGPB parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.aolais.electroraven.is2viewerbeta.protos.GeminiUniverseCurveDescriptorVGPB.GEMINI_UINVERSE_CURVE_DESCRIPTOR_VGPB parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.aolais.electroraven.is2viewerbeta.protos.GeminiUniverseCurveDescriptorVGPB.GEMINI_UINVERSE_CURVE_DESCRIPTOR_VGPB parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.aolais.electroraven.is2viewerbeta.protos.GeminiUniverseCurveDescriptorVGPB.GEMINI_UINVERSE_CURVE_DESCRIPTOR_VGPB parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.aolais.electroraven.is2viewerbeta.protos.GeminiUniverseCurveDescriptorVGPB.GEMINI_UINVERSE_CURVE_DESCRIPTOR_VGPB prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code GEMINI_UINVERSE_CURVE_DESCRIPTOR_VGPB}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:GEMINI_UINVERSE_CURVE_DESCRIPTOR_VGPB)
        com.aolais.electroraven.is2viewerbeta.protos.GeminiUniverseCurveDescriptorVGPB.GEMINI_UINVERSE_CURVE_DESCRIPTOR_VGPBOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.aolais.electroraven.is2viewerbeta.protos.GeminiUniverseCurveDescriptorVGPB.internal_static_GEMINI_UINVERSE_CURVE_DESCRIPTOR_VGPB_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.aolais.electroraven.is2viewerbeta.protos.GeminiUniverseCurveDescriptorVGPB.internal_static_GEMINI_UINVERSE_CURVE_DESCRIPTOR_VGPB_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.aolais.electroraven.is2viewerbeta.protos.GeminiUniverseCurveDescriptorVGPB.GEMINI_UINVERSE_CURVE_DESCRIPTOR_VGPB.class, com.aolais.electroraven.is2viewerbeta.protos.GeminiUniverseCurveDescriptorVGPB.GEMINI_UINVERSE_CURVE_DESCRIPTOR_VGPB.Builder.class);
      }

      // Construct using com.aolais.electroraven.is2viewerbeta.protos.GeminiUniverseCurveDescriptorVGPB.GEMINI_UINVERSE_CURVE_DESCRIPTOR_VGPB.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        startTempC_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000001);
        endTempC_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000002);
        u0_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000004);
        u1_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000008);
        u2_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.aolais.electroraven.is2viewerbeta.protos.GeminiUniverseCurveDescriptorVGPB.internal_static_GEMINI_UINVERSE_CURVE_DESCRIPTOR_VGPB_descriptor;
      }

      public com.aolais.electroraven.is2viewerbeta.protos.GeminiUniverseCurveDescriptorVGPB.GEMINI_UINVERSE_CURVE_DESCRIPTOR_VGPB getDefaultInstanceForType() {
        return com.aolais.electroraven.is2viewerbeta.protos.GeminiUniverseCurveDescriptorVGPB.GEMINI_UINVERSE_CURVE_DESCRIPTOR_VGPB.getDefaultInstance();
      }

      public com.aolais.electroraven.is2viewerbeta.protos.GeminiUniverseCurveDescriptorVGPB.GEMINI_UINVERSE_CURVE_DESCRIPTOR_VGPB build() {
        com.aolais.electroraven.is2viewerbeta.protos.GeminiUniverseCurveDescriptorVGPB.GEMINI_UINVERSE_CURVE_DESCRIPTOR_VGPB result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.aolais.electroraven.is2viewerbeta.protos.GeminiUniverseCurveDescriptorVGPB.GEMINI_UINVERSE_CURVE_DESCRIPTOR_VGPB buildPartial() {
        com.aolais.electroraven.is2viewerbeta.protos.GeminiUniverseCurveDescriptorVGPB.GEMINI_UINVERSE_CURVE_DESCRIPTOR_VGPB result = new com.aolais.electroraven.is2viewerbeta.protos.GeminiUniverseCurveDescriptorVGPB.GEMINI_UINVERSE_CURVE_DESCRIPTOR_VGPB(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.startTempC_ = startTempC_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.endTempC_ = endTempC_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.u0_ = u0_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.u1_ = u1_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.u2_ = u2_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.aolais.electroraven.is2viewerbeta.protos.GeminiUniverseCurveDescriptorVGPB.GEMINI_UINVERSE_CURVE_DESCRIPTOR_VGPB) {
          return mergeFrom((com.aolais.electroraven.is2viewerbeta.protos.GeminiUniverseCurveDescriptorVGPB.GEMINI_UINVERSE_CURVE_DESCRIPTOR_VGPB)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.aolais.electroraven.is2viewerbeta.protos.GeminiUniverseCurveDescriptorVGPB.GEMINI_UINVERSE_CURVE_DESCRIPTOR_VGPB other) {
        if (other == com.aolais.electroraven.is2viewerbeta.protos.GeminiUniverseCurveDescriptorVGPB.GEMINI_UINVERSE_CURVE_DESCRIPTOR_VGPB.getDefaultInstance()) return this;
        if (other.hasStartTempC()) {
          setStartTempC(other.getStartTempC());
        }
        if (other.hasEndTempC()) {
          setEndTempC(other.getEndTempC());
        }
        if (other.hasU0()) {
          setU0(other.getU0());
        }
        if (other.hasU1()) {
          setU1(other.getU1());
        }
        if (other.hasU2()) {
          setU2(other.getU2());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasStartTempC()) {
          
          return false;
        }
        if (!hasEndTempC()) {
          
          return false;
        }
        if (!hasU0()) {
          
          return false;
        }
        if (!hasU1()) {
          
          return false;
        }
        if (!hasU2()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.aolais.electroraven.is2viewerbeta.protos.GeminiUniverseCurveDescriptorVGPB.GEMINI_UINVERSE_CURVE_DESCRIPTOR_VGPB parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.aolais.electroraven.is2viewerbeta.protos.GeminiUniverseCurveDescriptorVGPB.GEMINI_UINVERSE_CURVE_DESCRIPTOR_VGPB) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private float startTempC_ ;
      /**
       * <code>required float startTempC = 1;</code>
       */
      public boolean hasStartTempC() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required float startTempC = 1;</code>
       */
      public float getStartTempC() {
        return startTempC_;
      }
      /**
       * <code>required float startTempC = 1;</code>
       */
      public Builder setStartTempC(float value) {
        bitField0_ |= 0x00000001;
        startTempC_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required float startTempC = 1;</code>
       */
      public Builder clearStartTempC() {
        bitField0_ = (bitField0_ & ~0x00000001);
        startTempC_ = 0F;
        onChanged();
        return this;
      }

      private float endTempC_ ;
      /**
       * <code>required float endTempC = 2;</code>
       */
      public boolean hasEndTempC() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required float endTempC = 2;</code>
       */
      public float getEndTempC() {
        return endTempC_;
      }
      /**
       * <code>required float endTempC = 2;</code>
       */
      public Builder setEndTempC(float value) {
        bitField0_ |= 0x00000002;
        endTempC_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required float endTempC = 2;</code>
       */
      public Builder clearEndTempC() {
        bitField0_ = (bitField0_ & ~0x00000002);
        endTempC_ = 0F;
        onChanged();
        return this;
      }

      private float u0_ ;
      /**
       * <code>required float U0 = 3;</code>
       */
      public boolean hasU0() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required float U0 = 3;</code>
       */
      public float getU0() {
        return u0_;
      }
      /**
       * <code>required float U0 = 3;</code>
       */
      public Builder setU0(float value) {
        bitField0_ |= 0x00000004;
        u0_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required float U0 = 3;</code>
       */
      public Builder clearU0() {
        bitField0_ = (bitField0_ & ~0x00000004);
        u0_ = 0F;
        onChanged();
        return this;
      }

      private float u1_ ;
      /**
       * <code>required float U1 = 4;</code>
       */
      public boolean hasU1() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required float U1 = 4;</code>
       */
      public float getU1() {
        return u1_;
      }
      /**
       * <code>required float U1 = 4;</code>
       */
      public Builder setU1(float value) {
        bitField0_ |= 0x00000008;
        u1_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required float U1 = 4;</code>
       */
      public Builder clearU1() {
        bitField0_ = (bitField0_ & ~0x00000008);
        u1_ = 0F;
        onChanged();
        return this;
      }

      private float u2_ ;
      /**
       * <code>required float U2 = 5;</code>
       */
      public boolean hasU2() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required float U2 = 5;</code>
       */
      public float getU2() {
        return u2_;
      }
      /**
       * <code>required float U2 = 5;</code>
       */
      public Builder setU2(float value) {
        bitField0_ |= 0x00000010;
        u2_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required float U2 = 5;</code>
       */
      public Builder clearU2() {
        bitField0_ = (bitField0_ & ~0x00000010);
        u2_ = 0F;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:GEMINI_UINVERSE_CURVE_DESCRIPTOR_VGPB)
    }

    static {
      defaultInstance = new GEMINI_UINVERSE_CURVE_DESCRIPTOR_VGPB(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:GEMINI_UINVERSE_CURVE_DESCRIPTOR_VGPB)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GEMINI_UINVERSE_CURVE_DESCRIPTOR_VGPB_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_GEMINI_UINVERSE_CURVE_DESCRIPTOR_VGPB_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n+GEMINI_UINVERSE_CURVE_DESCRIPTOR_VGPB." +
      "proto\"q\n%GEMINI_UINVERSE_CURVE_DESCRIPTO" +
      "R_VGPB\022\022\n\nstartTempC\030\001 \002(\002\022\020\n\010endTempC\030\002" +
      " \002(\002\022\n\n\002U0\030\003 \002(\002\022\n\n\002U1\030\004 \002(\002\022\n\n\002U2\030\005 \002(\002" +
      "BQ\n,com.aolais.electroraven.is2viewerbet" +
      "a.protosB!GeminiUniverseCurveDescriptorV" +
      "GPB"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_GEMINI_UINVERSE_CURVE_DESCRIPTOR_VGPB_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_GEMINI_UINVERSE_CURVE_DESCRIPTOR_VGPB_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_GEMINI_UINVERSE_CURVE_DESCRIPTOR_VGPB_descriptor,
        new java.lang.String[] { "StartTempC", "EndTempC", "U0", "U1", "U2", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
