// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: THERMAL_IMAGE_BASIC_PRESENTATION_FLAGS_VGPB.proto

package com.aolais.electroraven.is2viewerbeta.protos;

public final class ThermalImageBasicPresentationFlagsVGPB {
  private ThermalImageBasicPresentationFlagsVGPB() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface THERMAL_IMAGE_BASIC_PRESENTATION_FLAGS_VGPBOrBuilder extends
      // @@protoc_insertion_point(interface_extends:THERMAL_IMAGE_BASIC_PRESENTATION_FLAGS_VGPB)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 irAlphaLevel = 1;</code>
     */
    boolean hasIrAlphaLevel();
    /**
     * <code>required int32 irAlphaLevel = 1;</code>
     */
    int getIrAlphaLevel();

    /**
     * <code>required int32 languageCode = 2;</code>
     */
    boolean hasLanguageCode();
    /**
     * <code>required int32 languageCode = 2;</code>
     */
    int getLanguageCode();

    /**
     * <code>required int32 pipMode = 3;</code>
     */
    boolean hasPipMode();
    /**
     * <code>required int32 pipMode = 3;</code>
     */
    int getPipMode();

    /**
     * <code>required bool showRadiometricAnnotations = 4;</code>
     */
    boolean hasShowRadiometricAnnotations();
    /**
     * <code>required bool showRadiometricAnnotations = 4;</code>
     */
    boolean getShowRadiometricAnnotations();

    /**
     * <code>required int32 presentationTempUnits = 5;</code>
     */
    boolean hasPresentationTempUnits();
    /**
     * <code>required int32 presentationTempUnits = 5;</code>
     */
    int getPresentationTempUnits();

    /**
     * <code>required bool showCompass = 6;</code>
     */
    boolean hasShowCompass();
    /**
     * <code>required bool showCompass = 6;</code>
     */
    boolean getShowCompass();

    /**
     * <code>optional bool showLogo = 7;</code>
     */
    boolean hasShowLogo();
    /**
     * <code>optional bool showLogo = 7;</code>
     */
    boolean getShowLogo();
  }
  /**
   * Protobuf type {@code THERMAL_IMAGE_BASIC_PRESENTATION_FLAGS_VGPB}
   */
  public static final class THERMAL_IMAGE_BASIC_PRESENTATION_FLAGS_VGPB extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:THERMAL_IMAGE_BASIC_PRESENTATION_FLAGS_VGPB)
      THERMAL_IMAGE_BASIC_PRESENTATION_FLAGS_VGPBOrBuilder {
    // Use THERMAL_IMAGE_BASIC_PRESENTATION_FLAGS_VGPB.newBuilder() to construct.
    private THERMAL_IMAGE_BASIC_PRESENTATION_FLAGS_VGPB(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private THERMAL_IMAGE_BASIC_PRESENTATION_FLAGS_VGPB(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final THERMAL_IMAGE_BASIC_PRESENTATION_FLAGS_VGPB defaultInstance;
    public static THERMAL_IMAGE_BASIC_PRESENTATION_FLAGS_VGPB getDefaultInstance() {
      return defaultInstance;
    }

    public THERMAL_IMAGE_BASIC_PRESENTATION_FLAGS_VGPB getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private THERMAL_IMAGE_BASIC_PRESENTATION_FLAGS_VGPB(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              irAlphaLevel_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              languageCode_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              pipMode_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              showRadiometricAnnotations_ = input.readBool();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              presentationTempUnits_ = input.readInt32();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              showCompass_ = input.readBool();
              break;
            }
            case 56: {
              bitField0_ |= 0x00000040;
              showLogo_ = input.readBool();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.aolais.electroraven.is2viewerbeta.protos.ThermalImageBasicPresentationFlagsVGPB.internal_static_THERMAL_IMAGE_BASIC_PRESENTATION_FLAGS_VGPB_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.aolais.electroraven.is2viewerbeta.protos.ThermalImageBasicPresentationFlagsVGPB.internal_static_THERMAL_IMAGE_BASIC_PRESENTATION_FLAGS_VGPB_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.aolais.electroraven.is2viewerbeta.protos.ThermalImageBasicPresentationFlagsVGPB.THERMAL_IMAGE_BASIC_PRESENTATION_FLAGS_VGPB.class, com.aolais.electroraven.is2viewerbeta.protos.ThermalImageBasicPresentationFlagsVGPB.THERMAL_IMAGE_BASIC_PRESENTATION_FLAGS_VGPB.Builder.class);
    }

    public static com.google.protobuf.Parser<THERMAL_IMAGE_BASIC_PRESENTATION_FLAGS_VGPB> PARSER =
        new com.google.protobuf.AbstractParser<THERMAL_IMAGE_BASIC_PRESENTATION_FLAGS_VGPB>() {
      public THERMAL_IMAGE_BASIC_PRESENTATION_FLAGS_VGPB parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new THERMAL_IMAGE_BASIC_PRESENTATION_FLAGS_VGPB(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<THERMAL_IMAGE_BASIC_PRESENTATION_FLAGS_VGPB> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int IRALPHALEVEL_FIELD_NUMBER = 1;
    private int irAlphaLevel_;
    /**
     * <code>required int32 irAlphaLevel = 1;</code>
     */
    public boolean hasIrAlphaLevel() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 irAlphaLevel = 1;</code>
     */
    public int getIrAlphaLevel() {
      return irAlphaLevel_;
    }

    public static final int LANGUAGECODE_FIELD_NUMBER = 2;
    private int languageCode_;
    /**
     * <code>required int32 languageCode = 2;</code>
     */
    public boolean hasLanguageCode() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 languageCode = 2;</code>
     */
    public int getLanguageCode() {
      return languageCode_;
    }

    public static final int PIPMODE_FIELD_NUMBER = 3;
    private int pipMode_;
    /**
     * <code>required int32 pipMode = 3;</code>
     */
    public boolean hasPipMode() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int32 pipMode = 3;</code>
     */
    public int getPipMode() {
      return pipMode_;
    }

    public static final int SHOWRADIOMETRICANNOTATIONS_FIELD_NUMBER = 4;
    private boolean showRadiometricAnnotations_;
    /**
     * <code>required bool showRadiometricAnnotations = 4;</code>
     */
    public boolean hasShowRadiometricAnnotations() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required bool showRadiometricAnnotations = 4;</code>
     */
    public boolean getShowRadiometricAnnotations() {
      return showRadiometricAnnotations_;
    }

    public static final int PRESENTATIONTEMPUNITS_FIELD_NUMBER = 5;
    private int presentationTempUnits_;
    /**
     * <code>required int32 presentationTempUnits = 5;</code>
     */
    public boolean hasPresentationTempUnits() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required int32 presentationTempUnits = 5;</code>
     */
    public int getPresentationTempUnits() {
      return presentationTempUnits_;
    }

    public static final int SHOWCOMPASS_FIELD_NUMBER = 6;
    private boolean showCompass_;
    /**
     * <code>required bool showCompass = 6;</code>
     */
    public boolean hasShowCompass() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>required bool showCompass = 6;</code>
     */
    public boolean getShowCompass() {
      return showCompass_;
    }

    public static final int SHOWLOGO_FIELD_NUMBER = 7;
    private boolean showLogo_;
    /**
     * <code>optional bool showLogo = 7;</code>
     */
    public boolean hasShowLogo() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional bool showLogo = 7;</code>
     */
    public boolean getShowLogo() {
      return showLogo_;
    }

    private void initFields() {
      irAlphaLevel_ = 0;
      languageCode_ = 0;
      pipMode_ = 0;
      showRadiometricAnnotations_ = false;
      presentationTempUnits_ = 0;
      showCompass_ = false;
      showLogo_ = false;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasIrAlphaLevel()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLanguageCode()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPipMode()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasShowRadiometricAnnotations()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPresentationTempUnits()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasShowCompass()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, irAlphaLevel_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, languageCode_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, pipMode_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBool(4, showRadiometricAnnotations_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(5, presentationTempUnits_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBool(6, showCompass_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeBool(7, showLogo_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, irAlphaLevel_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, languageCode_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, pipMode_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(4, showRadiometricAnnotations_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, presentationTempUnits_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(6, showCompass_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(7, showLogo_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.aolais.electroraven.is2viewerbeta.protos.ThermalImageBasicPresentationFlagsVGPB.THERMAL_IMAGE_BASIC_PRESENTATION_FLAGS_VGPB parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.aolais.electroraven.is2viewerbeta.protos.ThermalImageBasicPresentationFlagsVGPB.THERMAL_IMAGE_BASIC_PRESENTATION_FLAGS_VGPB parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.aolais.electroraven.is2viewerbeta.protos.ThermalImageBasicPresentationFlagsVGPB.THERMAL_IMAGE_BASIC_PRESENTATION_FLAGS_VGPB parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.aolais.electroraven.is2viewerbeta.protos.ThermalImageBasicPresentationFlagsVGPB.THERMAL_IMAGE_BASIC_PRESENTATION_FLAGS_VGPB parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.aolais.electroraven.is2viewerbeta.protos.ThermalImageBasicPresentationFlagsVGPB.THERMAL_IMAGE_BASIC_PRESENTATION_FLAGS_VGPB parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.aolais.electroraven.is2viewerbeta.protos.ThermalImageBasicPresentationFlagsVGPB.THERMAL_IMAGE_BASIC_PRESENTATION_FLAGS_VGPB parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.aolais.electroraven.is2viewerbeta.protos.ThermalImageBasicPresentationFlagsVGPB.THERMAL_IMAGE_BASIC_PRESENTATION_FLAGS_VGPB parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.aolais.electroraven.is2viewerbeta.protos.ThermalImageBasicPresentationFlagsVGPB.THERMAL_IMAGE_BASIC_PRESENTATION_FLAGS_VGPB parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.aolais.electroraven.is2viewerbeta.protos.ThermalImageBasicPresentationFlagsVGPB.THERMAL_IMAGE_BASIC_PRESENTATION_FLAGS_VGPB parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.aolais.electroraven.is2viewerbeta.protos.ThermalImageBasicPresentationFlagsVGPB.THERMAL_IMAGE_BASIC_PRESENTATION_FLAGS_VGPB parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.aolais.electroraven.is2viewerbeta.protos.ThermalImageBasicPresentationFlagsVGPB.THERMAL_IMAGE_BASIC_PRESENTATION_FLAGS_VGPB prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code THERMAL_IMAGE_BASIC_PRESENTATION_FLAGS_VGPB}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:THERMAL_IMAGE_BASIC_PRESENTATION_FLAGS_VGPB)
        com.aolais.electroraven.is2viewerbeta.protos.ThermalImageBasicPresentationFlagsVGPB.THERMAL_IMAGE_BASIC_PRESENTATION_FLAGS_VGPBOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.aolais.electroraven.is2viewerbeta.protos.ThermalImageBasicPresentationFlagsVGPB.internal_static_THERMAL_IMAGE_BASIC_PRESENTATION_FLAGS_VGPB_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.aolais.electroraven.is2viewerbeta.protos.ThermalImageBasicPresentationFlagsVGPB.internal_static_THERMAL_IMAGE_BASIC_PRESENTATION_FLAGS_VGPB_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.aolais.electroraven.is2viewerbeta.protos.ThermalImageBasicPresentationFlagsVGPB.THERMAL_IMAGE_BASIC_PRESENTATION_FLAGS_VGPB.class, com.aolais.electroraven.is2viewerbeta.protos.ThermalImageBasicPresentationFlagsVGPB.THERMAL_IMAGE_BASIC_PRESENTATION_FLAGS_VGPB.Builder.class);
      }

      // Construct using com.aolais.electroraven.is2viewerbeta.protos.ThermalImageBasicPresentationFlagsVGPB.THERMAL_IMAGE_BASIC_PRESENTATION_FLAGS_VGPB.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        irAlphaLevel_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        languageCode_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        pipMode_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        showRadiometricAnnotations_ = false;
        bitField0_ = (bitField0_ & ~0x00000008);
        presentationTempUnits_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        showCompass_ = false;
        bitField0_ = (bitField0_ & ~0x00000020);
        showLogo_ = false;
        bitField0_ = (bitField0_ & ~0x00000040);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.aolais.electroraven.is2viewerbeta.protos.ThermalImageBasicPresentationFlagsVGPB.internal_static_THERMAL_IMAGE_BASIC_PRESENTATION_FLAGS_VGPB_descriptor;
      }

      public com.aolais.electroraven.is2viewerbeta.protos.ThermalImageBasicPresentationFlagsVGPB.THERMAL_IMAGE_BASIC_PRESENTATION_FLAGS_VGPB getDefaultInstanceForType() {
        return com.aolais.electroraven.is2viewerbeta.protos.ThermalImageBasicPresentationFlagsVGPB.THERMAL_IMAGE_BASIC_PRESENTATION_FLAGS_VGPB.getDefaultInstance();
      }

      public com.aolais.electroraven.is2viewerbeta.protos.ThermalImageBasicPresentationFlagsVGPB.THERMAL_IMAGE_BASIC_PRESENTATION_FLAGS_VGPB build() {
        com.aolais.electroraven.is2viewerbeta.protos.ThermalImageBasicPresentationFlagsVGPB.THERMAL_IMAGE_BASIC_PRESENTATION_FLAGS_VGPB result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.aolais.electroraven.is2viewerbeta.protos.ThermalImageBasicPresentationFlagsVGPB.THERMAL_IMAGE_BASIC_PRESENTATION_FLAGS_VGPB buildPartial() {
        com.aolais.electroraven.is2viewerbeta.protos.ThermalImageBasicPresentationFlagsVGPB.THERMAL_IMAGE_BASIC_PRESENTATION_FLAGS_VGPB result = new com.aolais.electroraven.is2viewerbeta.protos.ThermalImageBasicPresentationFlagsVGPB.THERMAL_IMAGE_BASIC_PRESENTATION_FLAGS_VGPB(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.irAlphaLevel_ = irAlphaLevel_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.languageCode_ = languageCode_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.pipMode_ = pipMode_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.showRadiometricAnnotations_ = showRadiometricAnnotations_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.presentationTempUnits_ = presentationTempUnits_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.showCompass_ = showCompass_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.showLogo_ = showLogo_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.aolais.electroraven.is2viewerbeta.protos.ThermalImageBasicPresentationFlagsVGPB.THERMAL_IMAGE_BASIC_PRESENTATION_FLAGS_VGPB) {
          return mergeFrom((com.aolais.electroraven.is2viewerbeta.protos.ThermalImageBasicPresentationFlagsVGPB.THERMAL_IMAGE_BASIC_PRESENTATION_FLAGS_VGPB)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.aolais.electroraven.is2viewerbeta.protos.ThermalImageBasicPresentationFlagsVGPB.THERMAL_IMAGE_BASIC_PRESENTATION_FLAGS_VGPB other) {
        if (other == com.aolais.electroraven.is2viewerbeta.protos.ThermalImageBasicPresentationFlagsVGPB.THERMAL_IMAGE_BASIC_PRESENTATION_FLAGS_VGPB.getDefaultInstance()) return this;
        if (other.hasIrAlphaLevel()) {
          setIrAlphaLevel(other.getIrAlphaLevel());
        }
        if (other.hasLanguageCode()) {
          setLanguageCode(other.getLanguageCode());
        }
        if (other.hasPipMode()) {
          setPipMode(other.getPipMode());
        }
        if (other.hasShowRadiometricAnnotations()) {
          setShowRadiometricAnnotations(other.getShowRadiometricAnnotations());
        }
        if (other.hasPresentationTempUnits()) {
          setPresentationTempUnits(other.getPresentationTempUnits());
        }
        if (other.hasShowCompass()) {
          setShowCompass(other.getShowCompass());
        }
        if (other.hasShowLogo()) {
          setShowLogo(other.getShowLogo());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasIrAlphaLevel()) {
          
          return false;
        }
        if (!hasLanguageCode()) {
          
          return false;
        }
        if (!hasPipMode()) {
          
          return false;
        }
        if (!hasShowRadiometricAnnotations()) {
          
          return false;
        }
        if (!hasPresentationTempUnits()) {
          
          return false;
        }
        if (!hasShowCompass()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.aolais.electroraven.is2viewerbeta.protos.ThermalImageBasicPresentationFlagsVGPB.THERMAL_IMAGE_BASIC_PRESENTATION_FLAGS_VGPB parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.aolais.electroraven.is2viewerbeta.protos.ThermalImageBasicPresentationFlagsVGPB.THERMAL_IMAGE_BASIC_PRESENTATION_FLAGS_VGPB) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int irAlphaLevel_ ;
      /**
       * <code>required int32 irAlphaLevel = 1;</code>
       */
      public boolean hasIrAlphaLevel() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 irAlphaLevel = 1;</code>
       */
      public int getIrAlphaLevel() {
        return irAlphaLevel_;
      }
      /**
       * <code>required int32 irAlphaLevel = 1;</code>
       */
      public Builder setIrAlphaLevel(int value) {
        bitField0_ |= 0x00000001;
        irAlphaLevel_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 irAlphaLevel = 1;</code>
       */
      public Builder clearIrAlphaLevel() {
        bitField0_ = (bitField0_ & ~0x00000001);
        irAlphaLevel_ = 0;
        onChanged();
        return this;
      }

      private int languageCode_ ;
      /**
       * <code>required int32 languageCode = 2;</code>
       */
      public boolean hasLanguageCode() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 languageCode = 2;</code>
       */
      public int getLanguageCode() {
        return languageCode_;
      }
      /**
       * <code>required int32 languageCode = 2;</code>
       */
      public Builder setLanguageCode(int value) {
        bitField0_ |= 0x00000002;
        languageCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 languageCode = 2;</code>
       */
      public Builder clearLanguageCode() {
        bitField0_ = (bitField0_ & ~0x00000002);
        languageCode_ = 0;
        onChanged();
        return this;
      }

      private int pipMode_ ;
      /**
       * <code>required int32 pipMode = 3;</code>
       */
      public boolean hasPipMode() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int32 pipMode = 3;</code>
       */
      public int getPipMode() {
        return pipMode_;
      }
      /**
       * <code>required int32 pipMode = 3;</code>
       */
      public Builder setPipMode(int value) {
        bitField0_ |= 0x00000004;
        pipMode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 pipMode = 3;</code>
       */
      public Builder clearPipMode() {
        bitField0_ = (bitField0_ & ~0x00000004);
        pipMode_ = 0;
        onChanged();
        return this;
      }

      private boolean showRadiometricAnnotations_ ;
      /**
       * <code>required bool showRadiometricAnnotations = 4;</code>
       */
      public boolean hasShowRadiometricAnnotations() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required bool showRadiometricAnnotations = 4;</code>
       */
      public boolean getShowRadiometricAnnotations() {
        return showRadiometricAnnotations_;
      }
      /**
       * <code>required bool showRadiometricAnnotations = 4;</code>
       */
      public Builder setShowRadiometricAnnotations(boolean value) {
        bitField0_ |= 0x00000008;
        showRadiometricAnnotations_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bool showRadiometricAnnotations = 4;</code>
       */
      public Builder clearShowRadiometricAnnotations() {
        bitField0_ = (bitField0_ & ~0x00000008);
        showRadiometricAnnotations_ = false;
        onChanged();
        return this;
      }

      private int presentationTempUnits_ ;
      /**
       * <code>required int32 presentationTempUnits = 5;</code>
       */
      public boolean hasPresentationTempUnits() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required int32 presentationTempUnits = 5;</code>
       */
      public int getPresentationTempUnits() {
        return presentationTempUnits_;
      }
      /**
       * <code>required int32 presentationTempUnits = 5;</code>
       */
      public Builder setPresentationTempUnits(int value) {
        bitField0_ |= 0x00000010;
        presentationTempUnits_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 presentationTempUnits = 5;</code>
       */
      public Builder clearPresentationTempUnits() {
        bitField0_ = (bitField0_ & ~0x00000010);
        presentationTempUnits_ = 0;
        onChanged();
        return this;
      }

      private boolean showCompass_ ;
      /**
       * <code>required bool showCompass = 6;</code>
       */
      public boolean hasShowCompass() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>required bool showCompass = 6;</code>
       */
      public boolean getShowCompass() {
        return showCompass_;
      }
      /**
       * <code>required bool showCompass = 6;</code>
       */
      public Builder setShowCompass(boolean value) {
        bitField0_ |= 0x00000020;
        showCompass_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bool showCompass = 6;</code>
       */
      public Builder clearShowCompass() {
        bitField0_ = (bitField0_ & ~0x00000020);
        showCompass_ = false;
        onChanged();
        return this;
      }

      private boolean showLogo_ ;
      /**
       * <code>optional bool showLogo = 7;</code>
       */
      public boolean hasShowLogo() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional bool showLogo = 7;</code>
       */
      public boolean getShowLogo() {
        return showLogo_;
      }
      /**
       * <code>optional bool showLogo = 7;</code>
       */
      public Builder setShowLogo(boolean value) {
        bitField0_ |= 0x00000040;
        showLogo_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool showLogo = 7;</code>
       */
      public Builder clearShowLogo() {
        bitField0_ = (bitField0_ & ~0x00000040);
        showLogo_ = false;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:THERMAL_IMAGE_BASIC_PRESENTATION_FLAGS_VGPB)
    }

    static {
      defaultInstance = new THERMAL_IMAGE_BASIC_PRESENTATION_FLAGS_VGPB(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:THERMAL_IMAGE_BASIC_PRESENTATION_FLAGS_VGPB)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_THERMAL_IMAGE_BASIC_PRESENTATION_FLAGS_VGPB_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_THERMAL_IMAGE_BASIC_PRESENTATION_FLAGS_VGPB_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n1THERMAL_IMAGE_BASIC_PRESENTATION_FLAGS" +
      "_VGPB.proto\"\324\001\n+THERMAL_IMAGE_BASIC_PRES" +
      "ENTATION_FLAGS_VGPB\022\024\n\014irAlphaLevel\030\001 \002(" +
      "\005\022\024\n\014languageCode\030\002 \002(\005\022\017\n\007pipMode\030\003 \002(\005" +
      "\022\"\n\032showRadiometricAnnotations\030\004 \002(\010\022\035\n\025" +
      "presentationTempUnits\030\005 \002(\005\022\023\n\013showCompa" +
      "ss\030\006 \002(\010\022\020\n\010showLogo\030\007 \001(\010BV\n,com.aolais" +
      ".electroraven.is2viewerbeta.protosB&Ther" +
      "malImageBasicPresentationFlagsVGPB"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_THERMAL_IMAGE_BASIC_PRESENTATION_FLAGS_VGPB_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_THERMAL_IMAGE_BASIC_PRESENTATION_FLAGS_VGPB_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_THERMAL_IMAGE_BASIC_PRESENTATION_FLAGS_VGPB_descriptor,
        new java.lang.String[] { "IrAlphaLevel", "LanguageCode", "PipMode", "ShowRadiometricAnnotations", "PresentationTempUnits", "ShowCompass", "ShowLogo", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
