// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: USER_DEFINED_MARKER_POINT.proto

package com.aolais.electroraven.is2viewerbeta.protos;

public final class UserDefinedMarkerPoint {
  private UserDefinedMarkerPoint() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface USER_DEFINED_MARKER_POINTOrBuilder extends
      // @@protoc_insertion_point(interface_extends:USER_DEFINED_MARKER_POINT)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required .PointStructure markerPixelIndex = 1;</code>
     */
    boolean hasMarkerPixelIndex();
    /**
     * <code>required .PointStructure markerPixelIndex = 1;</code>
     */
    com.aolais.electroraven.is2viewerbeta.protos.pointStructure.PointStructure getMarkerPixelIndex();
    /**
     * <code>required .PointStructure markerPixelIndex = 1;</code>
     */
    com.aolais.electroraven.is2viewerbeta.protos.pointStructure.PointStructureOrBuilder getMarkerPixelIndexOrBuilder();

    /**
     * <code>required .MARKER_COMMON_CHARACTERISTICS characteristics = 2;</code>
     */
    boolean hasCharacteristics();
    /**
     * <code>required .MARKER_COMMON_CHARACTERISTICS characteristics = 2;</code>
     */
    com.aolais.electroraven.is2viewerbeta.protos.MarkerCommonCharacteristics.MARKER_COMMON_CHARACTERISTICS getCharacteristics();
    /**
     * <code>required .MARKER_COMMON_CHARACTERISTICS characteristics = 2;</code>
     */
    com.aolais.electroraven.is2viewerbeta.protos.MarkerCommonCharacteristics.MARKER_COMMON_CHARACTERISTICSOrBuilder getCharacteristicsOrBuilder();
  }
  /**
   * Protobuf type {@code USER_DEFINED_MARKER_POINT}
   */
  public static final class USER_DEFINED_MARKER_POINT extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:USER_DEFINED_MARKER_POINT)
      USER_DEFINED_MARKER_POINTOrBuilder {
    // Use USER_DEFINED_MARKER_POINT.newBuilder() to construct.
    private USER_DEFINED_MARKER_POINT(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private USER_DEFINED_MARKER_POINT(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final USER_DEFINED_MARKER_POINT defaultInstance;
    public static USER_DEFINED_MARKER_POINT getDefaultInstance() {
      return defaultInstance;
    }

    public USER_DEFINED_MARKER_POINT getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private USER_DEFINED_MARKER_POINT(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.aolais.electroraven.is2viewerbeta.protos.pointStructure.PointStructure.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = markerPixelIndex_.toBuilder();
              }
              markerPixelIndex_ = input.readMessage(com.aolais.electroraven.is2viewerbeta.protos.pointStructure.PointStructure.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(markerPixelIndex_);
                markerPixelIndex_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
            case 18: {
              com.aolais.electroraven.is2viewerbeta.protos.MarkerCommonCharacteristics.MARKER_COMMON_CHARACTERISTICS.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) == 0x00000002)) {
                subBuilder = characteristics_.toBuilder();
              }
              characteristics_ = input.readMessage(com.aolais.electroraven.is2viewerbeta.protos.MarkerCommonCharacteristics.MARKER_COMMON_CHARACTERISTICS.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(characteristics_);
                characteristics_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.aolais.electroraven.is2viewerbeta.protos.UserDefinedMarkerPoint.internal_static_USER_DEFINED_MARKER_POINT_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.aolais.electroraven.is2viewerbeta.protos.UserDefinedMarkerPoint.internal_static_USER_DEFINED_MARKER_POINT_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.aolais.electroraven.is2viewerbeta.protos.UserDefinedMarkerPoint.USER_DEFINED_MARKER_POINT.class, com.aolais.electroraven.is2viewerbeta.protos.UserDefinedMarkerPoint.USER_DEFINED_MARKER_POINT.Builder.class);
    }

    public static com.google.protobuf.Parser<USER_DEFINED_MARKER_POINT> PARSER =
        new com.google.protobuf.AbstractParser<USER_DEFINED_MARKER_POINT>() {
      public USER_DEFINED_MARKER_POINT parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new USER_DEFINED_MARKER_POINT(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<USER_DEFINED_MARKER_POINT> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int MARKERPIXELINDEX_FIELD_NUMBER = 1;
    private com.aolais.electroraven.is2viewerbeta.protos.pointStructure.PointStructure markerPixelIndex_;
    /**
     * <code>required .PointStructure markerPixelIndex = 1;</code>
     */
    public boolean hasMarkerPixelIndex() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .PointStructure markerPixelIndex = 1;</code>
     */
    public com.aolais.electroraven.is2viewerbeta.protos.pointStructure.PointStructure getMarkerPixelIndex() {
      return markerPixelIndex_;
    }
    /**
     * <code>required .PointStructure markerPixelIndex = 1;</code>
     */
    public com.aolais.electroraven.is2viewerbeta.protos.pointStructure.PointStructureOrBuilder getMarkerPixelIndexOrBuilder() {
      return markerPixelIndex_;
    }

    public static final int CHARACTERISTICS_FIELD_NUMBER = 2;
    private com.aolais.electroraven.is2viewerbeta.protos.MarkerCommonCharacteristics.MARKER_COMMON_CHARACTERISTICS characteristics_;
    /**
     * <code>required .MARKER_COMMON_CHARACTERISTICS characteristics = 2;</code>
     */
    public boolean hasCharacteristics() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required .MARKER_COMMON_CHARACTERISTICS characteristics = 2;</code>
     */
    public com.aolais.electroraven.is2viewerbeta.protos.MarkerCommonCharacteristics.MARKER_COMMON_CHARACTERISTICS getCharacteristics() {
      return characteristics_;
    }
    /**
     * <code>required .MARKER_COMMON_CHARACTERISTICS characteristics = 2;</code>
     */
    public com.aolais.electroraven.is2viewerbeta.protos.MarkerCommonCharacteristics.MARKER_COMMON_CHARACTERISTICSOrBuilder getCharacteristicsOrBuilder() {
      return characteristics_;
    }

    private void initFields() {
      markerPixelIndex_ = com.aolais.electroraven.is2viewerbeta.protos.pointStructure.PointStructure.getDefaultInstance();
      characteristics_ = com.aolais.electroraven.is2viewerbeta.protos.MarkerCommonCharacteristics.MARKER_COMMON_CHARACTERISTICS.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasMarkerPixelIndex()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCharacteristics()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getMarkerPixelIndex().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getCharacteristics().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, markerPixelIndex_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, characteristics_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, markerPixelIndex_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, characteristics_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.aolais.electroraven.is2viewerbeta.protos.UserDefinedMarkerPoint.USER_DEFINED_MARKER_POINT parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.aolais.electroraven.is2viewerbeta.protos.UserDefinedMarkerPoint.USER_DEFINED_MARKER_POINT parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.aolais.electroraven.is2viewerbeta.protos.UserDefinedMarkerPoint.USER_DEFINED_MARKER_POINT parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.aolais.electroraven.is2viewerbeta.protos.UserDefinedMarkerPoint.USER_DEFINED_MARKER_POINT parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.aolais.electroraven.is2viewerbeta.protos.UserDefinedMarkerPoint.USER_DEFINED_MARKER_POINT parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.aolais.electroraven.is2viewerbeta.protos.UserDefinedMarkerPoint.USER_DEFINED_MARKER_POINT parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.aolais.electroraven.is2viewerbeta.protos.UserDefinedMarkerPoint.USER_DEFINED_MARKER_POINT parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.aolais.electroraven.is2viewerbeta.protos.UserDefinedMarkerPoint.USER_DEFINED_MARKER_POINT parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.aolais.electroraven.is2viewerbeta.protos.UserDefinedMarkerPoint.USER_DEFINED_MARKER_POINT parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.aolais.electroraven.is2viewerbeta.protos.UserDefinedMarkerPoint.USER_DEFINED_MARKER_POINT parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.aolais.electroraven.is2viewerbeta.protos.UserDefinedMarkerPoint.USER_DEFINED_MARKER_POINT prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code USER_DEFINED_MARKER_POINT}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:USER_DEFINED_MARKER_POINT)
        com.aolais.electroraven.is2viewerbeta.protos.UserDefinedMarkerPoint.USER_DEFINED_MARKER_POINTOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.aolais.electroraven.is2viewerbeta.protos.UserDefinedMarkerPoint.internal_static_USER_DEFINED_MARKER_POINT_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.aolais.electroraven.is2viewerbeta.protos.UserDefinedMarkerPoint.internal_static_USER_DEFINED_MARKER_POINT_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.aolais.electroraven.is2viewerbeta.protos.UserDefinedMarkerPoint.USER_DEFINED_MARKER_POINT.class, com.aolais.electroraven.is2viewerbeta.protos.UserDefinedMarkerPoint.USER_DEFINED_MARKER_POINT.Builder.class);
      }

      // Construct using com.aolais.electroraven.is2viewerbeta.protos.UserDefinedMarkerPoint.USER_DEFINED_MARKER_POINT.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getMarkerPixelIndexFieldBuilder();
          getCharacteristicsFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (markerPixelIndexBuilder_ == null) {
          markerPixelIndex_ = com.aolais.electroraven.is2viewerbeta.protos.pointStructure.PointStructure.getDefaultInstance();
        } else {
          markerPixelIndexBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        if (characteristicsBuilder_ == null) {
          characteristics_ = com.aolais.electroraven.is2viewerbeta.protos.MarkerCommonCharacteristics.MARKER_COMMON_CHARACTERISTICS.getDefaultInstance();
        } else {
          characteristicsBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.aolais.electroraven.is2viewerbeta.protos.UserDefinedMarkerPoint.internal_static_USER_DEFINED_MARKER_POINT_descriptor;
      }

      public com.aolais.electroraven.is2viewerbeta.protos.UserDefinedMarkerPoint.USER_DEFINED_MARKER_POINT getDefaultInstanceForType() {
        return com.aolais.electroraven.is2viewerbeta.protos.UserDefinedMarkerPoint.USER_DEFINED_MARKER_POINT.getDefaultInstance();
      }

      public com.aolais.electroraven.is2viewerbeta.protos.UserDefinedMarkerPoint.USER_DEFINED_MARKER_POINT build() {
        com.aolais.electroraven.is2viewerbeta.protos.UserDefinedMarkerPoint.USER_DEFINED_MARKER_POINT result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.aolais.electroraven.is2viewerbeta.protos.UserDefinedMarkerPoint.USER_DEFINED_MARKER_POINT buildPartial() {
        com.aolais.electroraven.is2viewerbeta.protos.UserDefinedMarkerPoint.USER_DEFINED_MARKER_POINT result = new com.aolais.electroraven.is2viewerbeta.protos.UserDefinedMarkerPoint.USER_DEFINED_MARKER_POINT(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (markerPixelIndexBuilder_ == null) {
          result.markerPixelIndex_ = markerPixelIndex_;
        } else {
          result.markerPixelIndex_ = markerPixelIndexBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (characteristicsBuilder_ == null) {
          result.characteristics_ = characteristics_;
        } else {
          result.characteristics_ = characteristicsBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.aolais.electroraven.is2viewerbeta.protos.UserDefinedMarkerPoint.USER_DEFINED_MARKER_POINT) {
          return mergeFrom((com.aolais.electroraven.is2viewerbeta.protos.UserDefinedMarkerPoint.USER_DEFINED_MARKER_POINT)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.aolais.electroraven.is2viewerbeta.protos.UserDefinedMarkerPoint.USER_DEFINED_MARKER_POINT other) {
        if (other == com.aolais.electroraven.is2viewerbeta.protos.UserDefinedMarkerPoint.USER_DEFINED_MARKER_POINT.getDefaultInstance()) return this;
        if (other.hasMarkerPixelIndex()) {
          mergeMarkerPixelIndex(other.getMarkerPixelIndex());
        }
        if (other.hasCharacteristics()) {
          mergeCharacteristics(other.getCharacteristics());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasMarkerPixelIndex()) {
          
          return false;
        }
        if (!hasCharacteristics()) {
          
          return false;
        }
        if (!getMarkerPixelIndex().isInitialized()) {
          
          return false;
        }
        if (!getCharacteristics().isInitialized()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.aolais.electroraven.is2viewerbeta.protos.UserDefinedMarkerPoint.USER_DEFINED_MARKER_POINT parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.aolais.electroraven.is2viewerbeta.protos.UserDefinedMarkerPoint.USER_DEFINED_MARKER_POINT) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.aolais.electroraven.is2viewerbeta.protos.pointStructure.PointStructure markerPixelIndex_ = com.aolais.electroraven.is2viewerbeta.protos.pointStructure.PointStructure.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.aolais.electroraven.is2viewerbeta.protos.pointStructure.PointStructure, com.aolais.electroraven.is2viewerbeta.protos.pointStructure.PointStructure.Builder, com.aolais.electroraven.is2viewerbeta.protos.pointStructure.PointStructureOrBuilder> markerPixelIndexBuilder_;
      /**
       * <code>required .PointStructure markerPixelIndex = 1;</code>
       */
      public boolean hasMarkerPixelIndex() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .PointStructure markerPixelIndex = 1;</code>
       */
      public com.aolais.electroraven.is2viewerbeta.protos.pointStructure.PointStructure getMarkerPixelIndex() {
        if (markerPixelIndexBuilder_ == null) {
          return markerPixelIndex_;
        } else {
          return markerPixelIndexBuilder_.getMessage();
        }
      }
      /**
       * <code>required .PointStructure markerPixelIndex = 1;</code>
       */
      public Builder setMarkerPixelIndex(com.aolais.electroraven.is2viewerbeta.protos.pointStructure.PointStructure value) {
        if (markerPixelIndexBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          markerPixelIndex_ = value;
          onChanged();
        } else {
          markerPixelIndexBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .PointStructure markerPixelIndex = 1;</code>
       */
      public Builder setMarkerPixelIndex(
          com.aolais.electroraven.is2viewerbeta.protos.pointStructure.PointStructure.Builder builderForValue) {
        if (markerPixelIndexBuilder_ == null) {
          markerPixelIndex_ = builderForValue.build();
          onChanged();
        } else {
          markerPixelIndexBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .PointStructure markerPixelIndex = 1;</code>
       */
      public Builder mergeMarkerPixelIndex(com.aolais.electroraven.is2viewerbeta.protos.pointStructure.PointStructure value) {
        if (markerPixelIndexBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              markerPixelIndex_ != com.aolais.electroraven.is2viewerbeta.protos.pointStructure.PointStructure.getDefaultInstance()) {
            markerPixelIndex_ =
              com.aolais.electroraven.is2viewerbeta.protos.pointStructure.PointStructure.newBuilder(markerPixelIndex_).mergeFrom(value).buildPartial();
          } else {
            markerPixelIndex_ = value;
          }
          onChanged();
        } else {
          markerPixelIndexBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .PointStructure markerPixelIndex = 1;</code>
       */
      public Builder clearMarkerPixelIndex() {
        if (markerPixelIndexBuilder_ == null) {
          markerPixelIndex_ = com.aolais.electroraven.is2viewerbeta.protos.pointStructure.PointStructure.getDefaultInstance();
          onChanged();
        } else {
          markerPixelIndexBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>required .PointStructure markerPixelIndex = 1;</code>
       */
      public com.aolais.electroraven.is2viewerbeta.protos.pointStructure.PointStructure.Builder getMarkerPixelIndexBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getMarkerPixelIndexFieldBuilder().getBuilder();
      }
      /**
       * <code>required .PointStructure markerPixelIndex = 1;</code>
       */
      public com.aolais.electroraven.is2viewerbeta.protos.pointStructure.PointStructureOrBuilder getMarkerPixelIndexOrBuilder() {
        if (markerPixelIndexBuilder_ != null) {
          return markerPixelIndexBuilder_.getMessageOrBuilder();
        } else {
          return markerPixelIndex_;
        }
      }
      /**
       * <code>required .PointStructure markerPixelIndex = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.aolais.electroraven.is2viewerbeta.protos.pointStructure.PointStructure, com.aolais.electroraven.is2viewerbeta.protos.pointStructure.PointStructure.Builder, com.aolais.electroraven.is2viewerbeta.protos.pointStructure.PointStructureOrBuilder> 
          getMarkerPixelIndexFieldBuilder() {
        if (markerPixelIndexBuilder_ == null) {
          markerPixelIndexBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.aolais.electroraven.is2viewerbeta.protos.pointStructure.PointStructure, com.aolais.electroraven.is2viewerbeta.protos.pointStructure.PointStructure.Builder, com.aolais.electroraven.is2viewerbeta.protos.pointStructure.PointStructureOrBuilder>(
                  getMarkerPixelIndex(),
                  getParentForChildren(),
                  isClean());
          markerPixelIndex_ = null;
        }
        return markerPixelIndexBuilder_;
      }

      private com.aolais.electroraven.is2viewerbeta.protos.MarkerCommonCharacteristics.MARKER_COMMON_CHARACTERISTICS characteristics_ = com.aolais.electroraven.is2viewerbeta.protos.MarkerCommonCharacteristics.MARKER_COMMON_CHARACTERISTICS.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.aolais.electroraven.is2viewerbeta.protos.MarkerCommonCharacteristics.MARKER_COMMON_CHARACTERISTICS, com.aolais.electroraven.is2viewerbeta.protos.MarkerCommonCharacteristics.MARKER_COMMON_CHARACTERISTICS.Builder, com.aolais.electroraven.is2viewerbeta.protos.MarkerCommonCharacteristics.MARKER_COMMON_CHARACTERISTICSOrBuilder> characteristicsBuilder_;
      /**
       * <code>required .MARKER_COMMON_CHARACTERISTICS characteristics = 2;</code>
       */
      public boolean hasCharacteristics() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required .MARKER_COMMON_CHARACTERISTICS characteristics = 2;</code>
       */
      public com.aolais.electroraven.is2viewerbeta.protos.MarkerCommonCharacteristics.MARKER_COMMON_CHARACTERISTICS getCharacteristics() {
        if (characteristicsBuilder_ == null) {
          return characteristics_;
        } else {
          return characteristicsBuilder_.getMessage();
        }
      }
      /**
       * <code>required .MARKER_COMMON_CHARACTERISTICS characteristics = 2;</code>
       */
      public Builder setCharacteristics(com.aolais.electroraven.is2viewerbeta.protos.MarkerCommonCharacteristics.MARKER_COMMON_CHARACTERISTICS value) {
        if (characteristicsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          characteristics_ = value;
          onChanged();
        } else {
          characteristicsBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>required .MARKER_COMMON_CHARACTERISTICS characteristics = 2;</code>
       */
      public Builder setCharacteristics(
          com.aolais.electroraven.is2viewerbeta.protos.MarkerCommonCharacteristics.MARKER_COMMON_CHARACTERISTICS.Builder builderForValue) {
        if (characteristicsBuilder_ == null) {
          characteristics_ = builderForValue.build();
          onChanged();
        } else {
          characteristicsBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>required .MARKER_COMMON_CHARACTERISTICS characteristics = 2;</code>
       */
      public Builder mergeCharacteristics(com.aolais.electroraven.is2viewerbeta.protos.MarkerCommonCharacteristics.MARKER_COMMON_CHARACTERISTICS value) {
        if (characteristicsBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              characteristics_ != com.aolais.electroraven.is2viewerbeta.protos.MarkerCommonCharacteristics.MARKER_COMMON_CHARACTERISTICS.getDefaultInstance()) {
            characteristics_ =
              com.aolais.electroraven.is2viewerbeta.protos.MarkerCommonCharacteristics.MARKER_COMMON_CHARACTERISTICS.newBuilder(characteristics_).mergeFrom(value).buildPartial();
          } else {
            characteristics_ = value;
          }
          onChanged();
        } else {
          characteristicsBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>required .MARKER_COMMON_CHARACTERISTICS characteristics = 2;</code>
       */
      public Builder clearCharacteristics() {
        if (characteristicsBuilder_ == null) {
          characteristics_ = com.aolais.electroraven.is2viewerbeta.protos.MarkerCommonCharacteristics.MARKER_COMMON_CHARACTERISTICS.getDefaultInstance();
          onChanged();
        } else {
          characteristicsBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      /**
       * <code>required .MARKER_COMMON_CHARACTERISTICS characteristics = 2;</code>
       */
      public com.aolais.electroraven.is2viewerbeta.protos.MarkerCommonCharacteristics.MARKER_COMMON_CHARACTERISTICS.Builder getCharacteristicsBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getCharacteristicsFieldBuilder().getBuilder();
      }
      /**
       * <code>required .MARKER_COMMON_CHARACTERISTICS characteristics = 2;</code>
       */
      public com.aolais.electroraven.is2viewerbeta.protos.MarkerCommonCharacteristics.MARKER_COMMON_CHARACTERISTICSOrBuilder getCharacteristicsOrBuilder() {
        if (characteristicsBuilder_ != null) {
          return characteristicsBuilder_.getMessageOrBuilder();
        } else {
          return characteristics_;
        }
      }
      /**
       * <code>required .MARKER_COMMON_CHARACTERISTICS characteristics = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.aolais.electroraven.is2viewerbeta.protos.MarkerCommonCharacteristics.MARKER_COMMON_CHARACTERISTICS, com.aolais.electroraven.is2viewerbeta.protos.MarkerCommonCharacteristics.MARKER_COMMON_CHARACTERISTICS.Builder, com.aolais.electroraven.is2viewerbeta.protos.MarkerCommonCharacteristics.MARKER_COMMON_CHARACTERISTICSOrBuilder> 
          getCharacteristicsFieldBuilder() {
        if (characteristicsBuilder_ == null) {
          characteristicsBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.aolais.electroraven.is2viewerbeta.protos.MarkerCommonCharacteristics.MARKER_COMMON_CHARACTERISTICS, com.aolais.electroraven.is2viewerbeta.protos.MarkerCommonCharacteristics.MARKER_COMMON_CHARACTERISTICS.Builder, com.aolais.electroraven.is2viewerbeta.protos.MarkerCommonCharacteristics.MARKER_COMMON_CHARACTERISTICSOrBuilder>(
                  getCharacteristics(),
                  getParentForChildren(),
                  isClean());
          characteristics_ = null;
        }
        return characteristicsBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:USER_DEFINED_MARKER_POINT)
    }

    static {
      defaultInstance = new USER_DEFINED_MARKER_POINT(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:USER_DEFINED_MARKER_POINT)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_USER_DEFINED_MARKER_POINT_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_USER_DEFINED_MARKER_POINT_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\037USER_DEFINED_MARKER_POINT.proto\032\024Point" +
      "Structure.proto\032#MARKER_COMMON_CHARACTER" +
      "ISTICS.proto\"\177\n\031USER_DEFINED_MARKER_POIN" +
      "T\022)\n\020markerPixelIndex\030\001 \002(\0132\017.PointStruc" +
      "ture\0227\n\017characteristics\030\002 \002(\0132\036.MARKER_C" +
      "OMMON_CHARACTERISTICSBF\n,com.aolais.elec" +
      "troraven.is2viewerbeta.protosB\026UserDefin" +
      "edMarkerPoint"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.aolais.electroraven.is2viewerbeta.protos.pointStructure.getDescriptor(),
          com.aolais.electroraven.is2viewerbeta.protos.MarkerCommonCharacteristics.getDescriptor(),
        }, assigner);
    internal_static_USER_DEFINED_MARKER_POINT_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_USER_DEFINED_MARKER_POINT_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_USER_DEFINED_MARKER_POINT_descriptor,
        new java.lang.String[] { "MarkerPixelIndex", "Characteristics", });
    com.aolais.electroraven.is2viewerbeta.protos.pointStructure.getDescriptor();
    com.aolais.electroraven.is2viewerbeta.protos.MarkerCommonCharacteristics.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
