// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: USER_DEFINED_MARKER_RECTANGLE.proto

package com.aolais.electroraven.is2viewerbeta.protos;

public final class UserDefinedMarkerRectangle {
  private UserDefinedMarkerRectangle() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface USER_DEFINED_MARKER_RECTANGLEOrBuilder extends
      // @@protoc_insertion_point(interface_extends:USER_DEFINED_MARKER_RECTANGLE)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required .PointStructure markerPixelIndexUL = 1;</code>
     */
    boolean hasMarkerPixelIndexUL();
    /**
     * <code>required .PointStructure markerPixelIndexUL = 1;</code>
     */
    com.aolais.electroraven.is2viewerbeta.protos.pointStructure.PointStructure getMarkerPixelIndexUL();
    /**
     * <code>required .PointStructure markerPixelIndexUL = 1;</code>
     */
    com.aolais.electroraven.is2viewerbeta.protos.pointStructure.PointStructureOrBuilder getMarkerPixelIndexULOrBuilder();

    /**
     * <code>required .PointStructure markerPixelIndexLR = 2;</code>
     */
    boolean hasMarkerPixelIndexLR();
    /**
     * <code>required .PointStructure markerPixelIndexLR = 2;</code>
     */
    com.aolais.electroraven.is2viewerbeta.protos.pointStructure.PointStructure getMarkerPixelIndexLR();
    /**
     * <code>required .PointStructure markerPixelIndexLR = 2;</code>
     */
    com.aolais.electroraven.is2viewerbeta.protos.pointStructure.PointStructureOrBuilder getMarkerPixelIndexLROrBuilder();

    /**
     * <code>required .MARKER_COMMON_CHARACTERISTICS characteristics = 3;</code>
     */
    boolean hasCharacteristics();
    /**
     * <code>required .MARKER_COMMON_CHARACTERISTICS characteristics = 3;</code>
     */
    com.aolais.electroraven.is2viewerbeta.protos.MarkerCommonCharacteristics.MARKER_COMMON_CHARACTERISTICS getCharacteristics();
    /**
     * <code>required .MARKER_COMMON_CHARACTERISTICS characteristics = 3;</code>
     */
    com.aolais.electroraven.is2viewerbeta.protos.MarkerCommonCharacteristics.MARKER_COMMON_CHARACTERISTICSOrBuilder getCharacteristicsOrBuilder();
  }
  /**
   * Protobuf type {@code USER_DEFINED_MARKER_RECTANGLE}
   */
  public static final class USER_DEFINED_MARKER_RECTANGLE extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:USER_DEFINED_MARKER_RECTANGLE)
      USER_DEFINED_MARKER_RECTANGLEOrBuilder {
    // Use USER_DEFINED_MARKER_RECTANGLE.newBuilder() to construct.
    private USER_DEFINED_MARKER_RECTANGLE(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private USER_DEFINED_MARKER_RECTANGLE(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final USER_DEFINED_MARKER_RECTANGLE defaultInstance;
    public static USER_DEFINED_MARKER_RECTANGLE getDefaultInstance() {
      return defaultInstance;
    }

    public USER_DEFINED_MARKER_RECTANGLE getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private USER_DEFINED_MARKER_RECTANGLE(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.aolais.electroraven.is2viewerbeta.protos.pointStructure.PointStructure.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = markerPixelIndexUL_.toBuilder();
              }
              markerPixelIndexUL_ = input.readMessage(com.aolais.electroraven.is2viewerbeta.protos.pointStructure.PointStructure.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(markerPixelIndexUL_);
                markerPixelIndexUL_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
            case 18: {
              com.aolais.electroraven.is2viewerbeta.protos.pointStructure.PointStructure.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) == 0x00000002)) {
                subBuilder = markerPixelIndexLR_.toBuilder();
              }
              markerPixelIndexLR_ = input.readMessage(com.aolais.electroraven.is2viewerbeta.protos.pointStructure.PointStructure.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(markerPixelIndexLR_);
                markerPixelIndexLR_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
            case 26: {
              com.aolais.electroraven.is2viewerbeta.protos.MarkerCommonCharacteristics.MARKER_COMMON_CHARACTERISTICS.Builder subBuilder = null;
              if (((bitField0_ & 0x00000004) == 0x00000004)) {
                subBuilder = characteristics_.toBuilder();
              }
              characteristics_ = input.readMessage(com.aolais.electroraven.is2viewerbeta.protos.MarkerCommonCharacteristics.MARKER_COMMON_CHARACTERISTICS.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(characteristics_);
                characteristics_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000004;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.aolais.electroraven.is2viewerbeta.protos.UserDefinedMarkerRectangle.internal_static_USER_DEFINED_MARKER_RECTANGLE_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.aolais.electroraven.is2viewerbeta.protos.UserDefinedMarkerRectangle.internal_static_USER_DEFINED_MARKER_RECTANGLE_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.aolais.electroraven.is2viewerbeta.protos.UserDefinedMarkerRectangle.USER_DEFINED_MARKER_RECTANGLE.class, com.aolais.electroraven.is2viewerbeta.protos.UserDefinedMarkerRectangle.USER_DEFINED_MARKER_RECTANGLE.Builder.class);
    }

    public static com.google.protobuf.Parser<USER_DEFINED_MARKER_RECTANGLE> PARSER =
        new com.google.protobuf.AbstractParser<USER_DEFINED_MARKER_RECTANGLE>() {
      public USER_DEFINED_MARKER_RECTANGLE parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new USER_DEFINED_MARKER_RECTANGLE(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<USER_DEFINED_MARKER_RECTANGLE> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int MARKERPIXELINDEXUL_FIELD_NUMBER = 1;
    private com.aolais.electroraven.is2viewerbeta.protos.pointStructure.PointStructure markerPixelIndexUL_;
    /**
     * <code>required .PointStructure markerPixelIndexUL = 1;</code>
     */
    public boolean hasMarkerPixelIndexUL() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .PointStructure markerPixelIndexUL = 1;</code>
     */
    public com.aolais.electroraven.is2viewerbeta.protos.pointStructure.PointStructure getMarkerPixelIndexUL() {
      return markerPixelIndexUL_;
    }
    /**
     * <code>required .PointStructure markerPixelIndexUL = 1;</code>
     */
    public com.aolais.electroraven.is2viewerbeta.protos.pointStructure.PointStructureOrBuilder getMarkerPixelIndexULOrBuilder() {
      return markerPixelIndexUL_;
    }

    public static final int MARKERPIXELINDEXLR_FIELD_NUMBER = 2;
    private com.aolais.electroraven.is2viewerbeta.protos.pointStructure.PointStructure markerPixelIndexLR_;
    /**
     * <code>required .PointStructure markerPixelIndexLR = 2;</code>
     */
    public boolean hasMarkerPixelIndexLR() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required .PointStructure markerPixelIndexLR = 2;</code>
     */
    public com.aolais.electroraven.is2viewerbeta.protos.pointStructure.PointStructure getMarkerPixelIndexLR() {
      return markerPixelIndexLR_;
    }
    /**
     * <code>required .PointStructure markerPixelIndexLR = 2;</code>
     */
    public com.aolais.electroraven.is2viewerbeta.protos.pointStructure.PointStructureOrBuilder getMarkerPixelIndexLROrBuilder() {
      return markerPixelIndexLR_;
    }

    public static final int CHARACTERISTICS_FIELD_NUMBER = 3;
    private com.aolais.electroraven.is2viewerbeta.protos.MarkerCommonCharacteristics.MARKER_COMMON_CHARACTERISTICS characteristics_;
    /**
     * <code>required .MARKER_COMMON_CHARACTERISTICS characteristics = 3;</code>
     */
    public boolean hasCharacteristics() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required .MARKER_COMMON_CHARACTERISTICS characteristics = 3;</code>
     */
    public com.aolais.electroraven.is2viewerbeta.protos.MarkerCommonCharacteristics.MARKER_COMMON_CHARACTERISTICS getCharacteristics() {
      return characteristics_;
    }
    /**
     * <code>required .MARKER_COMMON_CHARACTERISTICS characteristics = 3;</code>
     */
    public com.aolais.electroraven.is2viewerbeta.protos.MarkerCommonCharacteristics.MARKER_COMMON_CHARACTERISTICSOrBuilder getCharacteristicsOrBuilder() {
      return characteristics_;
    }

    private void initFields() {
      markerPixelIndexUL_ = com.aolais.electroraven.is2viewerbeta.protos.pointStructure.PointStructure.getDefaultInstance();
      markerPixelIndexLR_ = com.aolais.electroraven.is2viewerbeta.protos.pointStructure.PointStructure.getDefaultInstance();
      characteristics_ = com.aolais.electroraven.is2viewerbeta.protos.MarkerCommonCharacteristics.MARKER_COMMON_CHARACTERISTICS.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasMarkerPixelIndexUL()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMarkerPixelIndexLR()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCharacteristics()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getMarkerPixelIndexUL().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getMarkerPixelIndexLR().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getCharacteristics().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, markerPixelIndexUL_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, markerPixelIndexLR_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeMessage(3, characteristics_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, markerPixelIndexUL_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, markerPixelIndexLR_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, characteristics_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.aolais.electroraven.is2viewerbeta.protos.UserDefinedMarkerRectangle.USER_DEFINED_MARKER_RECTANGLE parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.aolais.electroraven.is2viewerbeta.protos.UserDefinedMarkerRectangle.USER_DEFINED_MARKER_RECTANGLE parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.aolais.electroraven.is2viewerbeta.protos.UserDefinedMarkerRectangle.USER_DEFINED_MARKER_RECTANGLE parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.aolais.electroraven.is2viewerbeta.protos.UserDefinedMarkerRectangle.USER_DEFINED_MARKER_RECTANGLE parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.aolais.electroraven.is2viewerbeta.protos.UserDefinedMarkerRectangle.USER_DEFINED_MARKER_RECTANGLE parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.aolais.electroraven.is2viewerbeta.protos.UserDefinedMarkerRectangle.USER_DEFINED_MARKER_RECTANGLE parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.aolais.electroraven.is2viewerbeta.protos.UserDefinedMarkerRectangle.USER_DEFINED_MARKER_RECTANGLE parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.aolais.electroraven.is2viewerbeta.protos.UserDefinedMarkerRectangle.USER_DEFINED_MARKER_RECTANGLE parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.aolais.electroraven.is2viewerbeta.protos.UserDefinedMarkerRectangle.USER_DEFINED_MARKER_RECTANGLE parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.aolais.electroraven.is2viewerbeta.protos.UserDefinedMarkerRectangle.USER_DEFINED_MARKER_RECTANGLE parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.aolais.electroraven.is2viewerbeta.protos.UserDefinedMarkerRectangle.USER_DEFINED_MARKER_RECTANGLE prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code USER_DEFINED_MARKER_RECTANGLE}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:USER_DEFINED_MARKER_RECTANGLE)
        com.aolais.electroraven.is2viewerbeta.protos.UserDefinedMarkerRectangle.USER_DEFINED_MARKER_RECTANGLEOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.aolais.electroraven.is2viewerbeta.protos.UserDefinedMarkerRectangle.internal_static_USER_DEFINED_MARKER_RECTANGLE_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.aolais.electroraven.is2viewerbeta.protos.UserDefinedMarkerRectangle.internal_static_USER_DEFINED_MARKER_RECTANGLE_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.aolais.electroraven.is2viewerbeta.protos.UserDefinedMarkerRectangle.USER_DEFINED_MARKER_RECTANGLE.class, com.aolais.electroraven.is2viewerbeta.protos.UserDefinedMarkerRectangle.USER_DEFINED_MARKER_RECTANGLE.Builder.class);
      }

      // Construct using com.aolais.electroraven.is2viewerbeta.protos.UserDefinedMarkerRectangle.USER_DEFINED_MARKER_RECTANGLE.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getMarkerPixelIndexULFieldBuilder();
          getMarkerPixelIndexLRFieldBuilder();
          getCharacteristicsFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (markerPixelIndexULBuilder_ == null) {
          markerPixelIndexUL_ = com.aolais.electroraven.is2viewerbeta.protos.pointStructure.PointStructure.getDefaultInstance();
        } else {
          markerPixelIndexULBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        if (markerPixelIndexLRBuilder_ == null) {
          markerPixelIndexLR_ = com.aolais.electroraven.is2viewerbeta.protos.pointStructure.PointStructure.getDefaultInstance();
        } else {
          markerPixelIndexLRBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        if (characteristicsBuilder_ == null) {
          characteristics_ = com.aolais.electroraven.is2viewerbeta.protos.MarkerCommonCharacteristics.MARKER_COMMON_CHARACTERISTICS.getDefaultInstance();
        } else {
          characteristicsBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.aolais.electroraven.is2viewerbeta.protos.UserDefinedMarkerRectangle.internal_static_USER_DEFINED_MARKER_RECTANGLE_descriptor;
      }

      public com.aolais.electroraven.is2viewerbeta.protos.UserDefinedMarkerRectangle.USER_DEFINED_MARKER_RECTANGLE getDefaultInstanceForType() {
        return com.aolais.electroraven.is2viewerbeta.protos.UserDefinedMarkerRectangle.USER_DEFINED_MARKER_RECTANGLE.getDefaultInstance();
      }

      public com.aolais.electroraven.is2viewerbeta.protos.UserDefinedMarkerRectangle.USER_DEFINED_MARKER_RECTANGLE build() {
        com.aolais.electroraven.is2viewerbeta.protos.UserDefinedMarkerRectangle.USER_DEFINED_MARKER_RECTANGLE result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.aolais.electroraven.is2viewerbeta.protos.UserDefinedMarkerRectangle.USER_DEFINED_MARKER_RECTANGLE buildPartial() {
        com.aolais.electroraven.is2viewerbeta.protos.UserDefinedMarkerRectangle.USER_DEFINED_MARKER_RECTANGLE result = new com.aolais.electroraven.is2viewerbeta.protos.UserDefinedMarkerRectangle.USER_DEFINED_MARKER_RECTANGLE(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (markerPixelIndexULBuilder_ == null) {
          result.markerPixelIndexUL_ = markerPixelIndexUL_;
        } else {
          result.markerPixelIndexUL_ = markerPixelIndexULBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (markerPixelIndexLRBuilder_ == null) {
          result.markerPixelIndexLR_ = markerPixelIndexLR_;
        } else {
          result.markerPixelIndexLR_ = markerPixelIndexLRBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        if (characteristicsBuilder_ == null) {
          result.characteristics_ = characteristics_;
        } else {
          result.characteristics_ = characteristicsBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.aolais.electroraven.is2viewerbeta.protos.UserDefinedMarkerRectangle.USER_DEFINED_MARKER_RECTANGLE) {
          return mergeFrom((com.aolais.electroraven.is2viewerbeta.protos.UserDefinedMarkerRectangle.USER_DEFINED_MARKER_RECTANGLE)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.aolais.electroraven.is2viewerbeta.protos.UserDefinedMarkerRectangle.USER_DEFINED_MARKER_RECTANGLE other) {
        if (other == com.aolais.electroraven.is2viewerbeta.protos.UserDefinedMarkerRectangle.USER_DEFINED_MARKER_RECTANGLE.getDefaultInstance()) return this;
        if (other.hasMarkerPixelIndexUL()) {
          mergeMarkerPixelIndexUL(other.getMarkerPixelIndexUL());
        }
        if (other.hasMarkerPixelIndexLR()) {
          mergeMarkerPixelIndexLR(other.getMarkerPixelIndexLR());
        }
        if (other.hasCharacteristics()) {
          mergeCharacteristics(other.getCharacteristics());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasMarkerPixelIndexUL()) {
          
          return false;
        }
        if (!hasMarkerPixelIndexLR()) {
          
          return false;
        }
        if (!hasCharacteristics()) {
          
          return false;
        }
        if (!getMarkerPixelIndexUL().isInitialized()) {
          
          return false;
        }
        if (!getMarkerPixelIndexLR().isInitialized()) {
          
          return false;
        }
        if (!getCharacteristics().isInitialized()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.aolais.electroraven.is2viewerbeta.protos.UserDefinedMarkerRectangle.USER_DEFINED_MARKER_RECTANGLE parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.aolais.electroraven.is2viewerbeta.protos.UserDefinedMarkerRectangle.USER_DEFINED_MARKER_RECTANGLE) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.aolais.electroraven.is2viewerbeta.protos.pointStructure.PointStructure markerPixelIndexUL_ = com.aolais.electroraven.is2viewerbeta.protos.pointStructure.PointStructure.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.aolais.electroraven.is2viewerbeta.protos.pointStructure.PointStructure, com.aolais.electroraven.is2viewerbeta.protos.pointStructure.PointStructure.Builder, com.aolais.electroraven.is2viewerbeta.protos.pointStructure.PointStructureOrBuilder> markerPixelIndexULBuilder_;
      /**
       * <code>required .PointStructure markerPixelIndexUL = 1;</code>
       */
      public boolean hasMarkerPixelIndexUL() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .PointStructure markerPixelIndexUL = 1;</code>
       */
      public com.aolais.electroraven.is2viewerbeta.protos.pointStructure.PointStructure getMarkerPixelIndexUL() {
        if (markerPixelIndexULBuilder_ == null) {
          return markerPixelIndexUL_;
        } else {
          return markerPixelIndexULBuilder_.getMessage();
        }
      }
      /**
       * <code>required .PointStructure markerPixelIndexUL = 1;</code>
       */
      public Builder setMarkerPixelIndexUL(com.aolais.electroraven.is2viewerbeta.protos.pointStructure.PointStructure value) {
        if (markerPixelIndexULBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          markerPixelIndexUL_ = value;
          onChanged();
        } else {
          markerPixelIndexULBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .PointStructure markerPixelIndexUL = 1;</code>
       */
      public Builder setMarkerPixelIndexUL(
          com.aolais.electroraven.is2viewerbeta.protos.pointStructure.PointStructure.Builder builderForValue) {
        if (markerPixelIndexULBuilder_ == null) {
          markerPixelIndexUL_ = builderForValue.build();
          onChanged();
        } else {
          markerPixelIndexULBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .PointStructure markerPixelIndexUL = 1;</code>
       */
      public Builder mergeMarkerPixelIndexUL(com.aolais.electroraven.is2viewerbeta.protos.pointStructure.PointStructure value) {
        if (markerPixelIndexULBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              markerPixelIndexUL_ != com.aolais.electroraven.is2viewerbeta.protos.pointStructure.PointStructure.getDefaultInstance()) {
            markerPixelIndexUL_ =
              com.aolais.electroraven.is2viewerbeta.protos.pointStructure.PointStructure.newBuilder(markerPixelIndexUL_).mergeFrom(value).buildPartial();
          } else {
            markerPixelIndexUL_ = value;
          }
          onChanged();
        } else {
          markerPixelIndexULBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .PointStructure markerPixelIndexUL = 1;</code>
       */
      public Builder clearMarkerPixelIndexUL() {
        if (markerPixelIndexULBuilder_ == null) {
          markerPixelIndexUL_ = com.aolais.electroraven.is2viewerbeta.protos.pointStructure.PointStructure.getDefaultInstance();
          onChanged();
        } else {
          markerPixelIndexULBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>required .PointStructure markerPixelIndexUL = 1;</code>
       */
      public com.aolais.electroraven.is2viewerbeta.protos.pointStructure.PointStructure.Builder getMarkerPixelIndexULBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getMarkerPixelIndexULFieldBuilder().getBuilder();
      }
      /**
       * <code>required .PointStructure markerPixelIndexUL = 1;</code>
       */
      public com.aolais.electroraven.is2viewerbeta.protos.pointStructure.PointStructureOrBuilder getMarkerPixelIndexULOrBuilder() {
        if (markerPixelIndexULBuilder_ != null) {
          return markerPixelIndexULBuilder_.getMessageOrBuilder();
        } else {
          return markerPixelIndexUL_;
        }
      }
      /**
       * <code>required .PointStructure markerPixelIndexUL = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.aolais.electroraven.is2viewerbeta.protos.pointStructure.PointStructure, com.aolais.electroraven.is2viewerbeta.protos.pointStructure.PointStructure.Builder, com.aolais.electroraven.is2viewerbeta.protos.pointStructure.PointStructureOrBuilder> 
          getMarkerPixelIndexULFieldBuilder() {
        if (markerPixelIndexULBuilder_ == null) {
          markerPixelIndexULBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.aolais.electroraven.is2viewerbeta.protos.pointStructure.PointStructure, com.aolais.electroraven.is2viewerbeta.protos.pointStructure.PointStructure.Builder, com.aolais.electroraven.is2viewerbeta.protos.pointStructure.PointStructureOrBuilder>(
                  getMarkerPixelIndexUL(),
                  getParentForChildren(),
                  isClean());
          markerPixelIndexUL_ = null;
        }
        return markerPixelIndexULBuilder_;
      }

      private com.aolais.electroraven.is2viewerbeta.protos.pointStructure.PointStructure markerPixelIndexLR_ = com.aolais.electroraven.is2viewerbeta.protos.pointStructure.PointStructure.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.aolais.electroraven.is2viewerbeta.protos.pointStructure.PointStructure, com.aolais.electroraven.is2viewerbeta.protos.pointStructure.PointStructure.Builder, com.aolais.electroraven.is2viewerbeta.protos.pointStructure.PointStructureOrBuilder> markerPixelIndexLRBuilder_;
      /**
       * <code>required .PointStructure markerPixelIndexLR = 2;</code>
       */
      public boolean hasMarkerPixelIndexLR() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required .PointStructure markerPixelIndexLR = 2;</code>
       */
      public com.aolais.electroraven.is2viewerbeta.protos.pointStructure.PointStructure getMarkerPixelIndexLR() {
        if (markerPixelIndexLRBuilder_ == null) {
          return markerPixelIndexLR_;
        } else {
          return markerPixelIndexLRBuilder_.getMessage();
        }
      }
      /**
       * <code>required .PointStructure markerPixelIndexLR = 2;</code>
       */
      public Builder setMarkerPixelIndexLR(com.aolais.electroraven.is2viewerbeta.protos.pointStructure.PointStructure value) {
        if (markerPixelIndexLRBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          markerPixelIndexLR_ = value;
          onChanged();
        } else {
          markerPixelIndexLRBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>required .PointStructure markerPixelIndexLR = 2;</code>
       */
      public Builder setMarkerPixelIndexLR(
          com.aolais.electroraven.is2viewerbeta.protos.pointStructure.PointStructure.Builder builderForValue) {
        if (markerPixelIndexLRBuilder_ == null) {
          markerPixelIndexLR_ = builderForValue.build();
          onChanged();
        } else {
          markerPixelIndexLRBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>required .PointStructure markerPixelIndexLR = 2;</code>
       */
      public Builder mergeMarkerPixelIndexLR(com.aolais.electroraven.is2viewerbeta.protos.pointStructure.PointStructure value) {
        if (markerPixelIndexLRBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              markerPixelIndexLR_ != com.aolais.electroraven.is2viewerbeta.protos.pointStructure.PointStructure.getDefaultInstance()) {
            markerPixelIndexLR_ =
              com.aolais.electroraven.is2viewerbeta.protos.pointStructure.PointStructure.newBuilder(markerPixelIndexLR_).mergeFrom(value).buildPartial();
          } else {
            markerPixelIndexLR_ = value;
          }
          onChanged();
        } else {
          markerPixelIndexLRBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>required .PointStructure markerPixelIndexLR = 2;</code>
       */
      public Builder clearMarkerPixelIndexLR() {
        if (markerPixelIndexLRBuilder_ == null) {
          markerPixelIndexLR_ = com.aolais.electroraven.is2viewerbeta.protos.pointStructure.PointStructure.getDefaultInstance();
          onChanged();
        } else {
          markerPixelIndexLRBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      /**
       * <code>required .PointStructure markerPixelIndexLR = 2;</code>
       */
      public com.aolais.electroraven.is2viewerbeta.protos.pointStructure.PointStructure.Builder getMarkerPixelIndexLRBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getMarkerPixelIndexLRFieldBuilder().getBuilder();
      }
      /**
       * <code>required .PointStructure markerPixelIndexLR = 2;</code>
       */
      public com.aolais.electroraven.is2viewerbeta.protos.pointStructure.PointStructureOrBuilder getMarkerPixelIndexLROrBuilder() {
        if (markerPixelIndexLRBuilder_ != null) {
          return markerPixelIndexLRBuilder_.getMessageOrBuilder();
        } else {
          return markerPixelIndexLR_;
        }
      }
      /**
       * <code>required .PointStructure markerPixelIndexLR = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.aolais.electroraven.is2viewerbeta.protos.pointStructure.PointStructure, com.aolais.electroraven.is2viewerbeta.protos.pointStructure.PointStructure.Builder, com.aolais.electroraven.is2viewerbeta.protos.pointStructure.PointStructureOrBuilder> 
          getMarkerPixelIndexLRFieldBuilder() {
        if (markerPixelIndexLRBuilder_ == null) {
          markerPixelIndexLRBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.aolais.electroraven.is2viewerbeta.protos.pointStructure.PointStructure, com.aolais.electroraven.is2viewerbeta.protos.pointStructure.PointStructure.Builder, com.aolais.electroraven.is2viewerbeta.protos.pointStructure.PointStructureOrBuilder>(
                  getMarkerPixelIndexLR(),
                  getParentForChildren(),
                  isClean());
          markerPixelIndexLR_ = null;
        }
        return markerPixelIndexLRBuilder_;
      }

      private com.aolais.electroraven.is2viewerbeta.protos.MarkerCommonCharacteristics.MARKER_COMMON_CHARACTERISTICS characteristics_ = com.aolais.electroraven.is2viewerbeta.protos.MarkerCommonCharacteristics.MARKER_COMMON_CHARACTERISTICS.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.aolais.electroraven.is2viewerbeta.protos.MarkerCommonCharacteristics.MARKER_COMMON_CHARACTERISTICS, com.aolais.electroraven.is2viewerbeta.protos.MarkerCommonCharacteristics.MARKER_COMMON_CHARACTERISTICS.Builder, com.aolais.electroraven.is2viewerbeta.protos.MarkerCommonCharacteristics.MARKER_COMMON_CHARACTERISTICSOrBuilder> characteristicsBuilder_;
      /**
       * <code>required .MARKER_COMMON_CHARACTERISTICS characteristics = 3;</code>
       */
      public boolean hasCharacteristics() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required .MARKER_COMMON_CHARACTERISTICS characteristics = 3;</code>
       */
      public com.aolais.electroraven.is2viewerbeta.protos.MarkerCommonCharacteristics.MARKER_COMMON_CHARACTERISTICS getCharacteristics() {
        if (characteristicsBuilder_ == null) {
          return characteristics_;
        } else {
          return characteristicsBuilder_.getMessage();
        }
      }
      /**
       * <code>required .MARKER_COMMON_CHARACTERISTICS characteristics = 3;</code>
       */
      public Builder setCharacteristics(com.aolais.electroraven.is2viewerbeta.protos.MarkerCommonCharacteristics.MARKER_COMMON_CHARACTERISTICS value) {
        if (characteristicsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          characteristics_ = value;
          onChanged();
        } else {
          characteristicsBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>required .MARKER_COMMON_CHARACTERISTICS characteristics = 3;</code>
       */
      public Builder setCharacteristics(
          com.aolais.electroraven.is2viewerbeta.protos.MarkerCommonCharacteristics.MARKER_COMMON_CHARACTERISTICS.Builder builderForValue) {
        if (characteristicsBuilder_ == null) {
          characteristics_ = builderForValue.build();
          onChanged();
        } else {
          characteristicsBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>required .MARKER_COMMON_CHARACTERISTICS characteristics = 3;</code>
       */
      public Builder mergeCharacteristics(com.aolais.electroraven.is2viewerbeta.protos.MarkerCommonCharacteristics.MARKER_COMMON_CHARACTERISTICS value) {
        if (characteristicsBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004) &&
              characteristics_ != com.aolais.electroraven.is2viewerbeta.protos.MarkerCommonCharacteristics.MARKER_COMMON_CHARACTERISTICS.getDefaultInstance()) {
            characteristics_ =
              com.aolais.electroraven.is2viewerbeta.protos.MarkerCommonCharacteristics.MARKER_COMMON_CHARACTERISTICS.newBuilder(characteristics_).mergeFrom(value).buildPartial();
          } else {
            characteristics_ = value;
          }
          onChanged();
        } else {
          characteristicsBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>required .MARKER_COMMON_CHARACTERISTICS characteristics = 3;</code>
       */
      public Builder clearCharacteristics() {
        if (characteristicsBuilder_ == null) {
          characteristics_ = com.aolais.electroraven.is2viewerbeta.protos.MarkerCommonCharacteristics.MARKER_COMMON_CHARACTERISTICS.getDefaultInstance();
          onChanged();
        } else {
          characteristicsBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      /**
       * <code>required .MARKER_COMMON_CHARACTERISTICS characteristics = 3;</code>
       */
      public com.aolais.electroraven.is2viewerbeta.protos.MarkerCommonCharacteristics.MARKER_COMMON_CHARACTERISTICS.Builder getCharacteristicsBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getCharacteristicsFieldBuilder().getBuilder();
      }
      /**
       * <code>required .MARKER_COMMON_CHARACTERISTICS characteristics = 3;</code>
       */
      public com.aolais.electroraven.is2viewerbeta.protos.MarkerCommonCharacteristics.MARKER_COMMON_CHARACTERISTICSOrBuilder getCharacteristicsOrBuilder() {
        if (characteristicsBuilder_ != null) {
          return characteristicsBuilder_.getMessageOrBuilder();
        } else {
          return characteristics_;
        }
      }
      /**
       * <code>required .MARKER_COMMON_CHARACTERISTICS characteristics = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.aolais.electroraven.is2viewerbeta.protos.MarkerCommonCharacteristics.MARKER_COMMON_CHARACTERISTICS, com.aolais.electroraven.is2viewerbeta.protos.MarkerCommonCharacteristics.MARKER_COMMON_CHARACTERISTICS.Builder, com.aolais.electroraven.is2viewerbeta.protos.MarkerCommonCharacteristics.MARKER_COMMON_CHARACTERISTICSOrBuilder> 
          getCharacteristicsFieldBuilder() {
        if (characteristicsBuilder_ == null) {
          characteristicsBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.aolais.electroraven.is2viewerbeta.protos.MarkerCommonCharacteristics.MARKER_COMMON_CHARACTERISTICS, com.aolais.electroraven.is2viewerbeta.protos.MarkerCommonCharacteristics.MARKER_COMMON_CHARACTERISTICS.Builder, com.aolais.electroraven.is2viewerbeta.protos.MarkerCommonCharacteristics.MARKER_COMMON_CHARACTERISTICSOrBuilder>(
                  getCharacteristics(),
                  getParentForChildren(),
                  isClean());
          characteristics_ = null;
        }
        return characteristicsBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:USER_DEFINED_MARKER_RECTANGLE)
    }

    static {
      defaultInstance = new USER_DEFINED_MARKER_RECTANGLE(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:USER_DEFINED_MARKER_RECTANGLE)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_USER_DEFINED_MARKER_RECTANGLE_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_USER_DEFINED_MARKER_RECTANGLE_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n#USER_DEFINED_MARKER_RECTANGLE.proto\032\024P" +
      "ointStructure.proto\032#MARKER_COMMON_CHARA" +
      "CTERISTICS.proto\"\262\001\n\035USER_DEFINED_MARKER" +
      "_RECTANGLE\022+\n\022markerPixelIndexUL\030\001 \002(\0132\017" +
      ".PointStructure\022+\n\022markerPixelIndexLR\030\002 " +
      "\002(\0132\017.PointStructure\0227\n\017characteristics\030" +
      "\003 \002(\0132\036.MARKER_COMMON_CHARACTERISTICSBJ\n" +
      ",com.aolais.electroraven.is2viewerbeta.p" +
      "rotosB\032UserDefinedMarkerRectangle"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.aolais.electroraven.is2viewerbeta.protos.pointStructure.getDescriptor(),
          com.aolais.electroraven.is2viewerbeta.protos.MarkerCommonCharacteristics.getDescriptor(),
        }, assigner);
    internal_static_USER_DEFINED_MARKER_RECTANGLE_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_USER_DEFINED_MARKER_RECTANGLE_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_USER_DEFINED_MARKER_RECTANGLE_descriptor,
        new java.lang.String[] { "MarkerPixelIndexUL", "MarkerPixelIndexLR", "Characteristics", });
    com.aolais.electroraven.is2viewerbeta.protos.pointStructure.getDescriptor();
    com.aolais.electroraven.is2viewerbeta.protos.MarkerCommonCharacteristics.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
